#Weekly Outbreaks data set

In [ ]:
import pandas as pd

df = pd.read_csv("/content/outbreak_clean (2).csv")

In [ ]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,Unique ID.,Name of \nState-UT,Name of \nDistrict,Disease- \nIllness,No. of \nCases,No. of \nDeaths,Date of Start \nof Outbreak,Date of \nReporting,Current \nStatus,Comments- Action Taken,NaN
1,BH/AUR/2025/40/1825,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,11,0,27-09-\n2025,04-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
2,BH/AUR/2025/40/1826,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,19,0,26-09-\n2025,03-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
3,CT/BAS/2025/40/1827,Chhattisgar\nh,Bastar,Leptospirosi\ns,5,0,29-09-\n2025,01-10-\n2025,Under \nControl,Cases \nwere \nreported \nfrom \nVillages \nDa...,NaN
4,GJ/CHH/2025/40/1828,Gujarat,Chhotaudep\nur,Suspected \nFood \nPoisoning,7,0,30-09-\n2025,30-09-\n2025,Under \nControl,Cases presenting with vomiting \nand weakn...,NaN
5,GJ/PAN/2025/40/1829,Gujarat,Panch \nMahals,Food \nPoisoning,63,0,28-09-\n2025,29-09-\n2025,Under \nSurveillance,Cases of vomiting \nand \nloose \nstools wer...,NaN
6,HR/KUR/2025/40/1830,Haryana,Kurukshetr\na,Leptospirosi\ns,68,0,30-09-\n2025,30-09-\n2025,Under \nSurveillance,Cases of fever with loose watery \nstool \nand...,NaN
7,JK/JAM/2025/40/1831,Jammu and \nKashmir,Jammu,Dengue,36,0,30-09-\n2025,03-10-\n2025,Under \nSurveillance,Cases of \nfever with bodyache \nwere repor...,NaN
8,JH/EAS/2025/40/1832,Jharkhand,East \nSinghbum,Acute \nDiarrhoeal \nDisease,22,0,01-10-\n2025,03-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
9,JH/EAS/2025/40/1833,Jharkhand,East \nSinghbum,Acute \nDiarrhoeal \nDisease,8,0,30-09-\n2025,01-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN

In [ ]:


# first row ko column names bana do
df.columns = df.iloc[0]

# first row remove
df = df[1:]

df.head()

,Unique ID.,Name of \nState-UT,Name of \nDistrict,Disease- \nIllness,No. of \nCases,No. of \nDeaths,Date of Start \nof Outbreak,Date of \nReporting,Current \nStatus,Comments- Action Taken,NaN
1,BH/AUR/2025/40/1825,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,11,0,27-09-\n2025,04-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
2,BH/AUR/2025/40/1826,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,19,0,26-09-\n2025,03-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
3,CT/BAS/2025/40/1827,Chhattisgar\nh,Bastar,Leptospirosi\ns,5,0,29-09-\n2025,01-10-\n2025,Under \nControl,Cases \nwere \nreported \nfrom \nVillages \nDa...,NaN
4,GJ/CHH/2025/40/1828,Gujarat,Chhotaudep\nur,Suspected \nFood \nPoisoning,7,0,30-09-\n2025,30-09-\n2025,Under \nControl,Cases presenting with vomiting \nand weakn...,NaN
5,GJ/PAN/2025/40/1829,Gujarat,Panch \nMahals,Food \nPoisoning,63,0,28-09-\n2025,29-09-\n2025,Under \nSurveillance,Cases of vomiting \nand \nloose \nstools wer...,NaN

In [ ]:
# newline remove
df.columns = df.columns.str.replace('\n', ' ', regex=True)

# extra spaces remove
df.columns = df.columns.str.strip()

df.columns

Index([                'Unique ID.',          'Name of  State-UT',
                'Name of  District',          'Disease-  Illness',
                    'No. of  Cases',             'No. of  Deaths',
       'Date of Start  of Outbreak',         'Date of  Reporting',
                  'Current  Status',     'Comments- Action Taken',
                                nan],
      dtype='object', name=0)

In [ ]:
df.columns = [
"unique_id",
"state",
"district",
"disease",
"cases",
"deaths",
"start_date",
"report_date",
"status",
"comments",
"extra"
]

df.head()

,unique_id,state,district,disease,cases,deaths,start_date,report_date,status,comments,extra
1,BH/AUR/2025/40/1825,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,11,0,27-09-\n2025,04-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
2,BH/AUR/2025/40/1826,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,19,0,26-09-\n2025,03-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...,NaN
3,CT/BAS/2025/40/1827,Chhattisgar\nh,Bastar,Leptospirosi\ns,5,0,29-09-\n2025,01-10-\n2025,Under \nControl,Cases \nwere \nreported \nfrom \nVillages \nDa...,NaN
4,GJ/CHH/2025/40/1828,Gujarat,Chhotaudep\nur,Suspected \nFood \nPoisoning,7,0,30-09-\n2025,30-09-\n2025,Under \nControl,Cases presenting with vomiting \nand weakn...,NaN
5,GJ/PAN/2025/40/1829,Gujarat,Panch \nMahals,Food \nPoisoning,63,0,28-09-\n2025,29-09-\n2025,Under \nSurveillance,Cases of vomiting \nand \nloose \nstools wer...,NaN

In [ ]:
df = df.drop(columns=["extra"])

In [ ]:
df.columns
df.head()

,unique_id,state,district,disease,cases,deaths,start_date,report_date,status,comments
1,BH/AUR/2025/40/1825,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,11,0,27-09-\n2025,04-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...
2,BH/AUR/2025/40/1826,Bihar,Aurangabad,Acute \nDiarrhoeal \nDisease,19,0,26-09-\n2025,03-10-\n2025,Under \nSurveillance,Cases \nof \nloose \nstools \nand \nvomiting ...
3,CT/BAS/2025/40/1827,Chhattisgar\nh,Bastar,Leptospirosi\ns,5,0,29-09-\n2025,01-10-\n2025,Under \nControl,Cases \nwere \nreported \nfrom \nVillages \nDa...
4,GJ/CHH/2025/40/1828,Gujarat,Chhotaudep\nur,Suspected \nFood \nPoisoning,7,0,30-09-\n2025,30-09-\n2025,Under \nControl,Cases presenting with vomiting \nand weakn...
5,GJ/PAN/2025/40/1829,Gujarat,Panch \nMahals,Food \nPoisoning,63,0,28-09-\n2025,29-09-\n2025,Under \nSurveillance,Cases of vomiting \nand \nloose \nstools wer...

In [ ]:
def clean_text(col):
    return (
        col.astype(str)
        .str.replace('\n', ' ', regex=True)   # newline remove
        .str.replace('\s+', ' ', regex=True)  # multiple spaces remove
        .str.strip()                          # leading/trailing space remove
        .str.lower()                          # lowercase
    )

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/1200004764.py:5: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+', ' ', regex=True)  # multiple spaces remove

In [ ]:
df['state'] = clean_text(df['state'])
df['district'] = clean_text(df['district'])
df['disease'] = clean_text(df['disease'])
df['status'] = clean_text(df['status'])

In [ ]:
df['comments'] = (
    df['comments']
    .astype(str)
    .str.replace('\n', ' ', regex=True)
    .str.replace('\s+', ' ', regex=True)
    .str.strip()
)

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/641560314.py:5: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+', ' ', regex=True)

In [ ]:
df[['state','district','disease','status']].head(10)

,state,district,disease,status
1,bihar,aurangabad,acute diarrhoeal disease,under surveillance
2,bihar,aurangabad,acute diarrhoeal disease,under surveillance
3,chhattisgar h,bastar,leptospirosi s,under control
4,gujarat,chhotaudep ur,suspected food poisoning,under control
5,gujarat,panch mahals,food poisoning,under surveillance
6,haryana,kurukshetr a,leptospirosi s,under surveillance
7,jammu and kashmir,jammu,dengue,under surveillance
8,jharkhand,east singhbum,acute diarrhoeal disease,under surveillance
9,jharkhand,east singhbum,acute diarrhoeal disease,under surveillance
10,jharkhand,east singhbum,acute diarrhoeal disease,under surveillance

In [ ]:
state_fix = {
    "chhattisgar h": "chhattisgarh"
}

In [ ]:
df['state'] = df['state'].replace(state_fix)

In [ ]:
district_fix = {
    "chhotaudep ur": "chhotaudepur",
    "kurukshetr a": "kurukshetra",
    "east singhbum": "east singhbhum",
    "panch mahals": "panchmahal"
}

In [ ]:
df['district'] = df['district'].replace(district_fix)

In [ ]:
disease_fix = {
    "leptospirosi s": "leptospirosis",
    "suspected food poisoning": "food poisoning"
}

In [ ]:
df['disease'] = df['disease'].replace(disease_fix)

In [ ]:
df[['state','district','disease']].head(10)

                state        district                   disease
1               bihar      aurangabad  acute diarrhoeal disease
2               bihar      aurangabad  acute diarrhoeal disease
3        chhattisgarh          bastar             leptospirosis
4             gujarat    chhotaudepur            food poisoning
5             gujarat      panchmahal            food poisoning
6             haryana     kurukshetra             leptospirosis
7   jammu and kashmir           jammu                    dengue
8           jharkhand  east singhbhum  acute diarrhoeal disease
9           jharkhand  east singhbhum  acute diarrhoeal disease
10          jharkhand  east singhbhum  acute diarrhoeal disease

In [ ]:
df['state'].unique()
df['district'].unique()

array(['aurangabad', 'bastar', 'chhotaudepur', 'panchmahal',
       'kurukshetra', 'jammu', 'east singhbhum', 'saraikela kharsawan',
       'ernakulam', 'malappura m', 'palakkad', 'chhatarpur', 'akola',
       'buldhana', 'dharashiv', 'deogarh', 'tenkasi', 'alipurduar', 'nan',
       'name of district', 'chhatrapati sambhajinag ar', 's.a.s nagar',
       'pilibhit', 'lakhimpur', 'patna', 'tapi', 'doda', 'kulgam',
       'srinagar', 'deoghar', 'dhanbad', 'dumka', 'giridih', 'koderma',
       'bengaluru urban', 'kannur', 'kasaragod', 'kottayam', 'kozhikode',
       'malappuram', 'thrissur', 'wayanad', 'ashoknagar', 'guna',
       'shivpuri', 'amravati', 'kolhapur', 'thane', 'north garo hills',
       'boudh', 'cuttack', 'sambalpur', 'faridkot', 'rupnagar',
       'bharatpur', 'madurai', 'tuticorin', 'purulia', 'purbi champaran',
       'bhopal', 'krishnagiri', 'longding', 'barpeta', 'dibrugarh',
       'sonitpur', 'mungeli', 'rajnandgao n', 'ahmadabad', 'yamunanag ar',
       'baramulla', 'kathua', 'shopian', 'garhwa', 'latehar', 'kolar',
       'mandya', 'pathanamth itta', 'dindori', 'mandla', 'narsinghpu r',
       'bhandara', 'gadchiroli', 'nagpur', 'nanded', 'imphal west',
       'baran', 'pratapgarh', 'anantapur', 'sri sathya sai', 'lohit',
       'raigarh', 'chikkamagal uru', 'chittoor', 'tirupati', 'cachar',
       'charaideo', 'golaghat', 'hojai', 'nalbari', 'baloda bazar',
       'devbhumi dwarka', 'gir somnath', 'hamirpur', 'kupwara', 'rajauri',
       'simdega', 'chikballapu r', 'pathanamthi tta', 'dhar', 'indore',
       'jabalpur', 'jhabua', 'umaria', 'vidisha', 'chandrapur', 'dhule',
       'pune', 'saitual', 'bhadrak', 'kendujhar', 'khordha',
       'nabarangpu r', 'coimbatore', 'west tripura', 'meerut', 'mirzapur',
       'rae bareli', 'kakinada', 'bongaigaon', 'ntr', 'visakhapa tanam',
       'y.s.r.', 'dhemaji', 'majuli', 'gaurella pendra marwahi',
       'mahasam und', 'panipat', 'ganderbal', 'sahebganj',
       'saraikela kharsawa n', 'belagavi', 'dharwad', 'raichur',
       'ernakula m', 'kollam', 'sheopur', 'sidhi', 'parbhani', 'yavatmal',
       'ganjam', 'mahe', 'pondicher ry', 'coimbator e', 'tirupathu r',
       'agar malwa', 'amritsar', 'ludhiana', 'parvathipuram manyam',
       'hailakandi', 'purnia', 'sabarkantha', 'badgam', 'khunti',
       'chikballapur', 'hassan', 'datia', 'gwalior', 'jalgaon', 'dimapur',
       'sri muktsar sahib', 'jalore', 'mayiladuthurai', 'ranipet',
       'tirupathur', 'south tripura', 'howrah', 'medinipur east',
       'medinipur west', 'paschim bardhaman', 'munger', 'bagalkot',
       'alappuzha', 'lawngtlai', 'malkangiri', 'konaseema', 'chirang',
       'darrang', 'jorhat', 'udalguri', 'begusarai', 'dhamtari',
       'kabirdham', 'south goa', 'amreli', 'hazaribagh', 'palamu',
       'kalaburagi', 'uttar kannad', 'vijayapura', 'thiruvananthap uram',
       'ratlam', 'palaghar', 'sangli', 'south garo hills', 'namakkal',
       'thanjavur', 'lalitpur', 'hooghly', 'nadia', 'narayanpur', 'betul',
       'papum pare', 'biswanath', 'kokrajhar', 'south east', 'jamtara',
       'thiruvananth apuram', 'burhanpur', 'narsinghpur', 'kalahandi',
       'pudukkottai', '24 paraganas north', 'purba bardhaman',
       'alirajpur', 'raipur', 'ahmedabad', 'jamnagar', 'patan',
       'chitradurga', 'davangere', 'senapati', 'west khasi hills',
       'salem', 'theni', 'dehradun', '24 paraganas south', 'tamulpur',
       'ranchi', 'gyalshing', 'balod', 'anand', 'arvalli', 'banas kantha',
       'gandhinagar', 'narmada', 'rajgarh', 'ujjain', 'kendrapara',
       'thiruvallur', 'tiruchirappal li', 'jhargram', 'sambhal',
       'name of state/ut', 'assam', 'chhattisgarh', 'gujarat',
       'jharkhand', 'karnataka', 'kerala', 'madhya pradesh',
       'maharashtra', 'meghalaya', 'nagaland', 'odisha', 'punjab',
       'sikkim', 'tamil nadu', 'uttar pradesh', 'west bengal',
       'alluri sitharama raju', 'kurnool', 'west siang', 'rajkot',
       'malappur am', 'khargone', 'saiha', 'jharsugud a',
       'tiruchirap palli', 'tiruvanna malai',
       'khairgarh chhuikhada n gandai', 'sonbhadra', 'lower subansiri',
       'gaya', 'jehanabad', 'pashchim champaran', 'rajnandgaon', 'valsad',
       'anantnag', 'pathanamthit ta', 'katni', 'neemuch', 'panna',
       'shahdol', 'raigad', 'bargarh', 'jagatsinghap ur', 'koraput',
       'soreng', 'tiruchirappa lli', 'mathura', 'guntur', 'palnadu',
       'banka', 'supaul', 'bhavnagar', 'surat', 'pulwama',
       'west singhbhu m', 'shivamogg a', 'idukki', 'burhanpu r',
       'east nimar', 'mandsaur', 'ukhrul', 'kendrapa ra', 'rayagada',
       'cuddalore', 'erode', 'alipurdua r', 'tirap', 'gopalganj',
       'jashpur', 'west singhbhum', 'thiruvanan thapuram', 'gangtok',
       'ananthapuram u', 'janjgir- champa', 'bidar', 'gadag', 'morena',
       'sundargarh', 'mayiladuthura i', 'villupuram',
       'gautam buddha nagar', 'ghaziabad', 'lucknow', 'karimganj',
       'godda', 'lohardaga', 'anugul', 'nuapada', 'nagapattinam',
       'sivaganga', 'farrukhabad', 'samastipur', 'patiala', 'durg',
       'mahasamund', 'mahesana', 'mysuru', 'sehore', 'satara',
       'tiruchirappalli', 'jamui', 'balrampur', 'madhubani', 'vaishali',
       'surguja', 'nuh', 'pathanamthitta', 'seoni', 'mumbai suburban',
       'east khasi hills', 'nandamuri taraka rama rao', 'visakhapatanam',
       'kamrup metro', 'nagaon', 'madhepura', 'raisen',
       'south west garo hills', 'west garo hills', 'jharsuguda',
       'ariyalur', 'kallakurichi', 'karur', 'virudhunagar',
       'sri potti sriramulu nellore', 'upper siang', 'gonda', 'bhagalpur',
       'kishanganj', 'bharuch', 'thiruvanant hapuram', 'damoh',
       'longleng', 'perambalur', 'the nilgiris', 'tirunelveli',
       'bilaspur', 'sonipat', 'yamunanagar', 'una', 'satna', 'washim',
       'kamjong', 'sonepur', 'dadra and nagar haveli', 'chandauli',
       'hapur', 'hardoi', 'jaunpur', 'jhansi', 'eluru', 'north tripura',
       'nandyal', 'dantewada', 'kachchh', 'panchmahals', 'dakshin kannad',
       'latur', 'jaipur', 'ramanathapura m', 'vellore', 'birbhum',
       'anuppur', 'bhadohi', 'pathanamt hitta', 'thiruvana nthapura m',
       'ashoknag ar', 'singrauli', 'palghar', 'sindhudur g', 'solapur',
       'balangir', 'kandham al', 'kallakuric hi', 'kanniyak umari',
       'villupura m', 'fatehpur', 'purba bardhama n', 'namsai',
       'junagadh', 'bandipora', 'chitradurg a', 'udupi', 'beed',
       'east jaintia hills', 'puri', 'pathanamthitt a', 'navsari',
       'niwari', 'gondia', 'ri bhoi', 'sitamarhi', 'bokaro', 'dharmapuri',
       'dindigul', 'kanniyakumari', 'rewa', 'parvathipur am manyam',
       'visakhapata nam', 'bhojpur', 'ajmer', 'udhampur', 'dhenkanal',
       'shravasti', 'coochbehar', 'kota', 'shamli', 'andhra pradesh',
       'arunachal pradesh', 'haryana', 'maharasht ra', 'goalpara',
       'tinsukia', 'jajapur', 'mayurbhanj', 'mayiladuthur ai', 'almora',
       'jalpaiguri', 'murshidabad', 'spsr nellore', 'changlang', 'bajali',
       'darbhanga', 'south west', 'rajsamand',
       'manendragar h chirimiri bharatpur', 'kheda', 'panchkula',
       'yamunanaga r', 'shajapur', 'jhalawar', 'mandi', 'anakapalli',
       'vadodara', 'gumla', 'koppal', 'vijayanaga r', 'chandrapu r',
       'kolasib', 'haveri', 'janjgir champa', 'kanker', 'tamenglong',
       'nayagarh', 'tiruvannam alai', 'noklak', 'rampur', 'coochbeha r',
       'north and middle andaman', 'bemetara', 'shivamogga', 'kandhamal',
       'dholpur', 'tiruchirappall i', 'basti', 'north goa', 'dohad',
       'bhind', 'korea', 'north', 'north west', 'kangra', 'nandurbar',
       'aizawl', 'pondicherry', 'siddharth nagar', 'kondagaon',
       'gurugram', 'poonch', 'west jaintia hills', 'tiruvannamalai',
       'pakke kessang', 'janjgir-champa', 'surendranagar',
       'thiruvananthapu ram', 'bankura', 'kaimur (bhabua)', 'kushi nagar',
       'parvathipura m manyam', 'surendranag ar', 'barwani', 'amethi',
       'prayagraj', 'leh ladakh', 'sabar kantha', 'yadgir', 'mon',
       'purbi champara n', 'chhotaude pur', 'chatra', 'bijapur',
       'yamunana gar', 'chikballap ur', 'vijayapur a', 'balaghat',
       'tikamgar h', 'eastern west khasi hills', 'mayurbha nj',
       'jhunjhunu', 'mohla manpur ambagarh chouki', 'east garo hills',
       'haridwar', 'churachandpur', 'agra', 'gandhinaga r', 'sirohi',
       'dhubri', 'karnal', 'hoshangabad', 'kanchipuram', 'south andamans',
       'saran', 'south', 'morbi', 'chhatrapati sambhajinaga r',
       'dima hasao', 'wardha', 'ambedkar nagar', 'moradabad',
       'muzaffarnagar', 'nabarangpur', 'prakasam', 'kamrup', 'dewas',
       'suryapet', 'chamoli', 'nicobars', 'katihar',
       'saraikelakha rsawan', 'kanchipura m', 'hyderabad', 'aligarh',
       'udam singh nagar', 'bongaigao n', 'kaithal', 'pathanam thitta',
       'karaikal', 'saharanpu r', 'mahisagar', 'shimla', 'tuensang',
       'auraiya', 'ballari', 'tumakuru', 'gajapati', 'maldah',
       'jagatsinghapur', 'dang', 'surendranaga r', 'kargil',
       'thiruvananthapura m', 'south west khasi hills', 'jalandhar',
       'udaipur'], dtype=object)

In [ ]:
invalid_values = [
'nan',
'name of district',
'name of state/ut'
]

df = df[~df['district'].isin(invalid_values)]

In [ ]:
df['district'] = df['district'].str.replace(' ', ' ')

In [ ]:
district_fix = {
"malappura m": "malappuram",
"ernakula m": "ernakulam",
"narsinghpu r": "narsinghpur",
"rajnandgao n": "rajnandgaon",
"visakhapa tanam": "visakhapatnam",
"tiruchirappal li": "tiruchirappalli",
"pathanamth itta": "pathanamthitta",
"nabarangpu r": "nabarangpur",
"mahasam und": "mahasamund",
"alipurdua r": "alipurduar",
"coimbator e": "coimbatore",
"thiruvananth apuram": "thiruvananthapuram"
}

df['district'] = df['district'].replace(district_fix)

In [ ]:
len(df['district'].unique())

593

In [ ]:
df['district'].unique()[:50]

array(['aurangabad', 'bastar', 'chhotaudepur', 'panchmahal',
       'kurukshetra', 'jammu', 'east singhbhum', 'saraikela kharsawan',
       'ernakulam', 'malappuram', 'palakkad', 'chhatarpur', 'akola',
       'buldhana', 'dharashiv', 'deogarh', 'tenkasi', 'alipurduar',
       'chhatrapati sambhajinag ar', 's.a.s nagar', 'pilibhit',
       'lakhimpur', 'patna', 'tapi', 'doda', 'kulgam', 'srinagar',
       'deoghar', 'dhanbad', 'dumka', 'giridih', 'koderma',
       'bengaluru urban', 'kannur', 'kasaragod', 'kottayam', 'kozhikode',
       'thrissur', 'wayanad', 'ashoknagar', 'guna', 'shivpuri',
       'amravati', 'kolhapur', 'thane', 'north garo hills', 'boudh',
       'cuttack', 'sambalpur', 'faridkot'], dtype=object)

In [ ]:
district_fix2 = {
    "chhatrapati sambhajinag ar": "chhatrapati sambhajinagar",
    "s.a.s nagar": "sas nagar"
}

df['district'] = df['district'].replace(district_fix2)

In [ ]:
df['district'].unique()[:50]

array(['aurangabad', 'bastar', 'chhotaudepur', 'panchmahal',
       'kurukshetra', 'jammu', 'east singhbhum', 'saraikela kharsawan',
       'ernakulam', 'malappuram', 'palakkad', 'chhatarpur', 'akola',
       'buldhana', 'dharashiv', 'deogarh', 'tenkasi', 'alipurduar',
       'chhatrapati sambhajinagar', 'sas nagar', 'pilibhit', 'lakhimpur',
       'patna', 'tapi', 'doda', 'kulgam', 'srinagar', 'deoghar',
       'dhanbad', 'dumka', 'giridih', 'koderma', 'bengaluru urban',
       'kannur', 'kasaragod', 'kottayam', 'kozhikode', 'thrissur',
       'wayanad', 'ashoknagar', 'guna', 'shivpuri', 'amravati',
       'kolhapur', 'thane', 'north garo hills', 'boudh', 'cuttack',
       'sambalpur', 'faridkot'], dtype=object)

In [ ]:
len(df['district'].unique())

593

In [ ]:
df[df['district'].str.contains('name', na=False)]

Empty DataFrame
Columns: [unique_id, state, district, disease, cases, deaths, start_date, report_date, status, comments]
Index: []

In [ ]:
df['district'].isna().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
print(sorted(df['state'].unique()))

['10. jh/gir/2025/04/104', '11. kl/ern/2025/04/105', '12. kl/ern/2025/04/106', '13. kl/ern/2025/04/107', '14. kl/idu/2025/04/108', '15. kl/kan/2025/04/109', '16. kl/kas/2025/04/110', '17. kl/kol/2025/04/111', '18. kl/kot/2025/04/112', '19. kl/mal/2025/04/113', '20. kl/pal/2025/04/114', '21. kl/pat/2025/04/115', '22. kl/thi/2025/04/116', '23. kl/way/2025/04/117', '24. kl/way/2025/04/118', '24. mp/dew/2025/22/938', '25. mp/dha/2025/04/119', '26. mp/din/2025/04/120', '27. mh/nan/2025/04/121', '27. mh/nan/2025/22/941', '28. mh/osm/2025/04/122', '28. mh/tha/2025/22/942', '29. mg/nor/2025/22/943', '29. mh/pal/2025/04/123', '30. mh/san/2025/04/124', '31. mg/ewk/2025/04/125', '32. or/cut/2025/04/126', '33. or/ken/2025/04/127', '34. or/nab/2025/04/128', '35. or/nau/2025/04/129', '36. or/ray/2025/04/130', '37. or/ray/2025/04/131', '38. tn/pud/2025/04/132', '39. tn/siv/2025/04/133', '40. tn/siv/2025/04/134', '41. tn/tha/2025/04/135', '42. tn/thn/2025/04/136', '43. wb/mew/2025/04/137', 'a', 'andaman & nicobar islands', 'andhra pradesh', 'ap/viz/2025/04/95', 'ar/eka/2025/04/96', 'arunachal pradesh', 'as/bak/2025/22/915', 'as/bon/2025/04/97', 'as/goa/2025/22/916', 'as/goa/2025/22/917', 'as/hai/2025/04/98', 'as/tin/2025/04/99', 'assam', 'bihar', 'bihar chhattis garh gujarat gujarat', 'chhattis garh', 'chhattisga rh', 'chhattisgarh', 'ct/bas/2025/22/918', 'ct/bil/2025/22/919', 'ct/bil/2025/22/920', 'd&n haveli', 'delhi', 'gj/bha/2025/04/100', 'gj/jun/2025/22/921', 'gj/mor/2025/22/922', 'gj/sur/2025/22/923', 'goa', 'gujarat', 'haryana', 'himachal pradesh', 'hr/kar/2025/04/101', 'jammu and kashmir', 'jh/cha/2025/04/102', 'jh/eas/2025/22/924', 'jh/eas/2025/22/925', 'jh/gar/2025/04/103', 'jh/khu/2025/22/926', 'jh/kod/2025/22/927', 'jharkha nd', 'jharkhand', 'karnata ka', 'karnataka', 'kerala', 'kerala kerala kerala kerala', 'kl/ern/2025/22/929', 'kl/ern/2025/22/930', 'kl/idu/2025/22/931', 'kl/kas/2025/22/932', 'kl/kol/2025/44/1996', 'kl/kot/2025/22/933', 'kl/kot/2025/22/934', 'kl/kot/2025/22/935', 'kl/koz/2025/22/936', 'kl/thr/2025/22/937', 'kn/has/2025/22/928', 'ladakh', 'madhya pradesh', 'maharas htra', 'maharasht ra', 'maharashtr a', 'maharashtra', 'manipur', 'meghalaya', 'mg/rib/2025/22/944', 'mh/jal/2025/22/940', 'mh/kol/2025/18/769 maharashtra', 'mizoram', 'mp/nar/2025/22/939', 'nagaland', 'nan', 'nl/koh/2025/22/945', 'odisha', 'or/anu/2025/22/946', 'or/anu/2025/22/947', 'or/jha/2025/22/948', 'pb/pat/2025/22/949', 'puducherry', 'punjab', 'rajastha n tamil nadu tamil nadu tamil nadu', 'rajasthan', 'sikkim', 'sk/pak/2025/22/950', 'tamil nadu', 'telangana', 'the dadra and nagar haveli and daman and diu', 'tn/may/2025/22/951', 'tripura', 'up/pra/2025/22/952', 'uttar pradesh', 'uttarakhan d', 'uttarakhand', 'wb/ali/2025/22/953', 'wb/ali/2025/22/954', 'wb/how/2025/43/1952 west bengal', 'wb/jha/2025/22/955', 'wb/pur/2025/22/956', 'wb/pur/2025/31/1440 west bengal', 'wb/pur/2025/31/1441 west bengal', 'west bengal']

In [ ]:
valid_states = [
'andhra pradesh','arunachal pradesh','assam','bihar','chhattisgarh',
'goa','gujarat','haryana','himachal pradesh','jharkhand','karnataka',
'kerala','madhya pradesh','maharashtra','manipur','meghalaya',
'mizoram','nagaland','odisha','punjab','rajasthan','sikkim',
'tamil nadu','telangana','tripura','uttar pradesh','uttarakhand',
'west bengal','delhi','ladakh','puducherry','andaman & nicobar islands',
'dadra and nagar haveli and daman and diu','jammu and kashmir'
]

In [ ]:
df['state'] = (
    df['state']
    .str.replace('\n',' ')
    .str.replace('\s+',' ', regex=True)
    .str.strip()
    .str.lower()
)

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/4102136949.py:4: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+',' ', regex=True)

In [ ]:
state_fix = {
'chhattis garh':'chhattisgarh',
'chhattisga rh':'chhattisgarh',
'jharkha nd':'jharkhand',
'karnata ka':'karnataka',
'maharas htra':'maharashtra',
'maharasht ra':'maharashtra',
'maharashtr a':'maharashtra',
'uttarakhan d':'uttarakhand'
}

df['state'] = df['state'].replace(state_fix)

In [ ]:
df = df[df['state'].isin(valid_states)]

In [ ]:
print(sorted(df['state'].unique()))
print("Total States:", df['state'].nunique())

['andaman & nicobar islands', 'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chhattisgarh', 'delhi', 'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jammu and kashmir', 'jharkhand', 'karnataka', 'kerala', 'ladakh', 'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal']
Total States: 33

In [ ]:
df[df['district'].isin(['nan','a','north','south','east','west'])]

,unique_id,state,district,disease,cases,deaths,start_date,report_date,status,comments
1852,DL/NOR/2025/39/1791,delhi,north,food poisoning,233,0,23-09-\n2025,24-09-\n2025,under surveillance,"Cases of loose motion, vomiting and vertigo we..."
2372,DL/SOU/2025/18/747,delhi,south,food poisoning,NaN,30-04-2025,30-04-2025,Under \nSurveillance,cases were reported from a college hostel in s...,nan

In [ ]:
invalid_districts = ['nan','a','north','south','east','west']

df = df[~df['district'].isin(invalid_districts)]

In [ ]:
df['district'] = (
    df['district']
    .str.replace('\n',' ')
    .str.replace('\s+',' ', regex=True)
    .str.strip()
    .str.lower()
)

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/1613729476.py:4: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+',' ', regex=True)

In [ ]:
print(sorted(df['district'].unique()))

['24 paraganas north', '24 paraganas south', 'agar malwa', 'agra', 'ahmadabad', 'ahmedabad', 'aizawl', 'ajmer', 'akola', 'alappuzha', 'aligarh', 'alipurduar', 'alirajpur', 'alluri sitharama raju', 'almora', 'ambedkar nagar', 'amethi', 'amravati', 'amreli', 'amritsar', 'anakapalli', 'anand', 'anantapur', 'ananthapuram u', 'anantnag', 'anugul', 'anuppur', 'ariyalur', 'arvalli', 'ashoknag ar', 'ashoknagar', 'auraiya', 'aurangabad', 'badgam', 'bagalkot', 'bajali', 'balaghat', 'balangir', 'ballari', 'balod', 'baloda bazar', 'balrampur', 'banas kantha', 'bandipora', 'banka', 'bankura', 'baramulla', 'baran', 'bargarh', 'barpeta', 'barwani', 'bastar', 'basti', 'beed', 'begusarai', 'belagavi', 'bemetara', 'bengaluru urban', 'betul', 'bhadohi', 'bhadrak', 'bhagalpur', 'bhandara', 'bharatpur', 'bharuch', 'bhavnagar', 'bhind', 'bhojpur', 'bhopal', 'bidar', 'bijapur', 'bilaspur', 'birbhum', 'biswanath', 'bokaro', 'bongaigao n', 'bongaigaon', 'boudh', 'buldhana', 'burhanpu r', 'burhanpur', 'cachar', 'chamoli', 'chandauli', 'chandrapu r', 'chandrapur', 'changlang', 'charaideo', 'chatra', 'chhatarpur', 'chhatrapati sambhajinagar', 'chhotaude pur', 'chhotaudepur', 'chikballap ur', 'chikballapu r', 'chikballapur', 'chikkamagal uru', 'chirang', 'chitradurg a', 'chitradurga', 'chittoor', 'churachandpur', 'coimbatore', 'coochbeha r', 'coochbehar', 'cuddalore', 'cuttack', 'dakshin kannad', 'damoh', 'dang', 'dantewada', 'darbhanga', 'darrang', 'datia', 'davangere', 'dehradun', 'deogarh', 'deoghar', 'devbhumi dwarka', 'dewas', 'dhamtari', 'dhanbad', 'dhar', 'dharashiv', 'dharmapuri', 'dharwad', 'dhemaji', 'dhenkanal', 'dholpur', 'dhubri', 'dhule', 'dibrugarh', 'dima hasao', 'dimapur', 'dindigul', 'dindori', 'doda', 'dohad', 'dumka', 'durg', 'east garo hills', 'east jaintia hills', 'east khasi hills', 'east nimar', 'east singhbhum', 'eastern west khasi hills', 'eluru', 'ernakulam', 'erode', 'faridkot', 'farrukhabad', 'fatehpur', 'gadag', 'gadchiroli', 'gajapati', 'ganderbal', 'gandhinagar', 'gangtok', 'ganjam', 'garhwa', 'gaurella pendra marwahi', 'gautam buddha nagar', 'gaya', 'ghaziabad', 'gir somnath', 'giridih', 'goalpara', 'godda', 'golaghat', 'gonda', 'gondia', 'gopalganj', 'gumla', 'guna', 'guntur', 'gurugram', 'gwalior', 'gyalshing', 'hailakandi', 'hamirpur', 'hapur', 'hardoi', 'haridwar', 'hassan', 'haveri', 'hazaribagh', 'hojai', 'hooghly', 'hoshangabad', 'howrah', 'hyderabad', 'idukki', 'imphal west', 'indore', 'jabalpur', 'jagatsinghap ur', 'jagatsinghapur', 'jaipur', 'jajapur', 'jalandhar', 'jalgaon', 'jalore', 'jalpaiguri', 'jammu', 'jamnagar', 'jamtara', 'jamui', 'janjgir champa', 'janjgir- champa', 'janjgir-champa', 'jashpur', 'jaunpur', 'jehanabad', 'jhabua', 'jhalawar', 'jhansi', 'jhargram', 'jharsugud a', 'jharsuguda', 'jhunjhunu', 'jorhat', 'junagadh', 'kabirdham', 'kachchh', 'kaimur (bhabua)', 'kaithal', 'kakinada', 'kalaburagi', 'kalahandi', 'kallakuric hi', 'kallakurichi', 'kamjong', 'kamrup', 'kamrup metro', 'kanchipura m', 'kanchipuram', 'kandham al', 'kandhamal', 'kangra', 'kanker', 'kanniyak umari', 'kanniyakumari', 'kannur', 'karaikal', 'kargil', 'karimganj', 'karnal', 'karur', 'kasaragod', 'kathua', 'katihar', 'katni', 'kendrapa ra', 'kendrapara', 'kendujhar', 'khairgarh chhuikhada n gandai', 'khargone', 'kheda', 'khordha', 'khunti', 'kishanganj', 'koderma', 'kokrajhar', 'kolar', 'kolasib', 'kolhapur', 'kollam', 'konaseema', 'kondagaon', 'koppal', 'koraput', 'korea', 'kota', 'kottayam', 'kozhikode', 'krishnagiri', 'kulgam', 'kupwara', 'kurnool', 'kurukshetra', 'kushi nagar', 'lakhimpur', 'lalitpur', 'latehar', 'latur', 'lawngtlai', 'leh ladakh', 'lohardaga', 'lohit', 'longding', 'longleng', 'lower subansiri', 'lucknow', 'ludhiana', 'madhepura', 'madhubani', 'madurai', 'mahasamund', 'mahe', 'mahesana', 'mahisagar', 'majuli', 'malappur am', 'malappuram', 'maldah', 'malkangiri', 'mandi', 'mandla', 'mandsaur', 'mandya', 'manendragar h chirimiri bharatpur', 'mathura', 'mayiladuthur ai', 'mayiladuthura i', 'mayiladuthurai', 'mayurbha nj', 'mayurbhanj', 'medinipur east', 'medinipur west', 'meerut', 'mirzapur', 'mohla manpur ambagarh chouki', 'mon', 'moradabad', 'morbi', 'morena', 'mumbai suburban', 'mungeli', 'munger', 'murshidabad', 'muzaffarnagar', 'mysuru', 'nabarangpur', 'nadia', 'nagaon', 'nagapattinam', 'nagpur', 'nalbari', 'namakkal', 'namsai', 'nandamuri taraka rama rao', 'nanded', 'nandurbar', 'nandyal', 'narayanpur', 'narmada', 'narsinghpur', 'navsari', 'nayagarh', 'neemuch', 'nicobars', 'niwari', 'noklak', 'north and middle andaman', 'north garo hills', 'north goa', 'north tripura', 'north west', 'ntr', 'nuapada', 'nuh', 'pakke kessang', 'palaghar', 'palakkad', 'palamu', 'palghar', 'palnadu', 'panchkula', 'panchmahal', 'panchmahals', 'panipat', 'panna', 'papum pare', 'parbhani', 'parvathipur am manyam', 'parvathipura m manyam', 'parvathipuram manyam', 'paschim bardhaman', 'pashchim champaran', 'patan', 'pathanam thitta', 'pathanamt hitta', 'pathanamthi tta', 'pathanamthit ta', 'pathanamthitt a', 'pathanamthitta', 'patiala', 'patna', 'perambalur', 'pilibhit', 'pondicher ry', 'pondicherry', 'poonch', 'prakasam', 'pratapgarh', 'prayagraj', 'pudukkottai', 'pulwama', 'pune', 'purba bardhama n', 'purba bardhaman', 'purbi champara n', 'purbi champaran', 'puri', 'purnia', 'purulia', 'rae bareli', 'raichur', 'raigad', 'raigarh', 'raipur', 'raisen', 'rajauri', 'rajgarh', 'rajkot', 'rajnandgaon', 'rajsamand', 'ramanathapura m', 'rampur', 'ranchi', 'ranipet', 'ratlam', 'rayagada', 'rewa', 'ri bhoi', 'rupnagar', 'sabar kantha', 'sabarkantha', 'saharanpu r', 'sahebganj', 'saiha', 'saitual', 'salem', 'samastipur', 'sambalpur', 'sambhal', 'sangli', 'saraikela kharsawa n', 'saraikela kharsawan', 'saraikelakha rsawan', 'saran', 'sas nagar', 'satara', 'satna', 'sehore', 'senapati', 'seoni', 'shahdol', 'shajapur', 'shamli', 'sheopur', 'shimla', 'shivamogg a', 'shivamogga', 'shivpuri', 'shopian', 'shravasti', 'siddharth nagar', 'sidhi', 'simdega', 'sindhudur g', 'singrauli', 'sitamarhi', 'sivaganga', 'solapur', 'sonbhadra', 'sonepur', 'sonipat', 'sonitpur', 'soreng', 'south andamans', 'south east', 'south garo hills', 'south goa', 'south tripura', 'south west', 'south west garo hills', 'south west khasi hills', 'spsr nellore', 'sri muktsar sahib', 'sri potti sriramulu nellore', 'sri sathya sai', 'srinagar', 'sundargarh', 'supaul', 'surat', 'surendranag ar', 'surendranaga r', 'surendranagar', 'surguja', 'suryapet', 'tamenglong', 'tamulpur', 'tapi', 'tenkasi', 'thane', 'thanjavur', 'the nilgiris', 'theni', 'thiruvallur', 'thiruvana nthapura m', 'thiruvanan thapuram', 'thiruvanant hapuram', 'thiruvananthap uram', 'thiruvananthapu ram', 'thiruvananthapura m', 'thiruvananthapuram', 'thrissur', 'tikamgar h', 'tinsukia', 'tirap', 'tiruchirap palli', 'tiruchirappa lli', 'tiruchirappall i', 'tiruchirappalli', 'tirunelveli', 'tirupathu r', 'tirupathur', 'tirupati', 'tiruvanna malai', 'tiruvannam alai', 'tiruvannamalai', 'tuensang', 'tumakuru', 'tuticorin', 'udaipur', 'udalguri', 'udam singh nagar', 'udhampur', 'udupi', 'ujjain', 'ukhrul', 'umaria', 'una', 'upper siang', 'uttar kannad', 'vadodara', 'vaishali', 'valsad', 'vellore', 'vidisha', 'vijayanaga r', 'vijayapur a', 'vijayapura', 'villupura m', 'villupuram', 'virudhunagar', 'visakhapata nam', 'visakhapatanam', 'visakhapatnam', 'wardha', 'washim', 'wayanad', 'west garo hills', 'west jaintia hills', 'west khasi hills', 'west siang', 'west singhbhu m', 'west singhbhum', 'west tripura', 'y.s.r.', 'yadgir', 'yamunana gar', 'yamunanag ar', 'yamunanaga r', 'yamunanagar', 'yavatmal']

In [ ]:
print("Total Districts:", df['district'].nunique())

Total Districts: 567

In [ ]:
df['district'] = (
    df['district']
    .str.replace(r'(\w)\s+(\w)', r'\1\2', regex=True)
)

In [ ]:
district_fix = {
"ahmadabad":"ahmedabad",
"panchmahals":"panchmahal",
"palaghar":"palghar",
"visakhapatanam":"visakhapatnam"
}

df['district'] = df['district'].replace(district_fix)

In [ ]:
print(len(df['district'].unique()))
print(sorted(df['district'].unique())[:50])

509
['24paraganasnorth', '24paraganassouth', 'agarmalwa', 'agra', 'ahmedabad', 'aizawl', 'ajmer', 'akola', 'alappuzha', 'aligarh', 'alipurduar', 'alirajpur', 'allurisitharamaraju', 'almora', 'ambedkarnagar', 'amethi', 'amravati', 'amreli', 'amritsar', 'anakapalli', 'anand', 'anantapur', 'ananthapuramu', 'anantnag', 'anugul', 'anuppur', 'ariyalur', 'arvalli', 'ashoknagar', 'auraiya', 'aurangabad', 'badgam', 'bagalkot', 'bajali', 'balaghat', 'balangir', 'ballari', 'balod', 'balodabazar', 'balrampur', 'banaskantha', 'bandipora', 'banka', 'bankura', 'baramulla', 'baran', 'bargarh', 'barpeta', 'barwani', 'bastar']

In [ ]:
df['district'] = df['district'].str.replace(r'(\w)\s+(\w)', r'\1\2', regex=True)

In [ ]:
df['district'] = (
    df['district']
    .str.replace('\n', ' ', regex=True)
    .str.replace('\s+', ' ', regex=True)
    .str.strip()
    .str.lower()
)

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/1135988195.py:4: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+', ' ', regex=True)

In [ ]:
df['district'] = df['district'].str.replace(r'(\w)\s+(\w)', r'\1\2', regex=True)

In [ ]:
print(len(df['district'].unique()))
print(df['district'].unique()[:30])

508
['aurangabad' 'bastar' 'chhotaudepur' 'panchmahal' 'kurukshetra' 'jammu'
 'eastsinghbhum' 'saraikelakharsawan' 'ernakulam' 'malappuram' 'palakkad'
 'chhatarpur' 'akola' 'buldhana' 'dharashiv' 'deogarh' 'tenkasi'
 'alipurduar' 'chhatrapatisambhajinagar' 'sasnagar' 'pilibhit' 'lakhimpur'
 'patna' 'tapi' 'doda' 'kulgam' 'srinagar' 'deoghar' 'dhanbad' 'dumka']

In [ ]:
district_fix = {
"eastsinghbhum":"east singhbhum",
"saraikelakharsawan":"saraikela kharsawan",
"chhatrapatisambhajinagar":"chhatrapati sambhajinagar",
"sasnagar":"sas nagar"
}

df['district'] = df['district'].replace(district_fix)

In [ ]:
print(df['district'].unique()[:30])

['aurangabad' 'bastar' 'chhotaudepur' 'panchmahal' 'kurukshetra' 'jammu'
 'east singhbhum' 'saraikela kharsawan' 'ernakulam' 'malappuram'
 'palakkad' 'chhatarpur' 'akola' 'buldhana' 'dharashiv' 'deogarh'
 'tenkasi' 'alipurduar' 'chhatrapati sambhajinagar' 'sas nagar' 'pilibhit'
 'lakhimpur' 'patna' 'tapi' 'doda' 'kulgam' 'srinagar' 'deoghar' 'dhanbad'
 'dumka']

In [ ]:
df.head()

,unique_id,state,district,disease,cases,deaths,start_date,report_date,status,comments
1,BH/AUR/2025/40/1825,bihar,aurangabad,acute diarrhoeal disease,11,0,27-09-\n2025,04-10-\n2025,under surveillance,Cases of loose stools and vomiting were report...
2,BH/AUR/2025/40/1826,bihar,aurangabad,acute diarrhoeal disease,19,0,26-09-\n2025,03-10-\n2025,under surveillance,Cases of loose stools and vomiting were report...
3,CT/BAS/2025/40/1827,chhattisgarh,bastar,leptospirosis,5,0,29-09-\n2025,01-10-\n2025,under control,"Cases were reported from Villages Dabaguda, Ma..."
4,GJ/CHH/2025/40/1828,gujarat,chhotaudepur,food poisoning,7,0,30-09-\n2025,30-09-\n2025,under control,Cases presenting with vomiting and weakness we...
5,GJ/PAN/2025/40/1829,gujarat,panchmahal,food poisoning,63,0,28-09-\n2025,29-09-\n2025,under surveillance,Cases of vomiting and loose stools were report...

In [ ]:
df = df.drop(columns=['unique_id'])

In [ ]:
df.columns

Index(['state', 'district', 'disease', 'cases', 'deaths', 'start_date',
       'report_date', 'status', 'comments'],
      dtype='object')

In [ ]:
sorted(df['disease'].unique())

['acute diarrheal disease',
 'acute diarrheal disease (shigellosis)',
 'acute diarrheal diseases',
 'acute diarrhoeal disease',
 'acute encephalitic syndrome',
 'acute encephalitic syndrome (suspected chpv)',
 'acute encephalitis syndrome',
 'acute gastroente ritis',
 'acute gastroenter itis',
 'acute gastroenteri tis',
 'acute gastroenterit is',
 'acute gastroenterit is (norovirus)',
 'acute gastroenteriti s',
 'acute gastroenteritis',
 'acute hepatitis',
 'acute hepatitis a',
 'acute hepatitis e',
 'c hikungunya',
 'chandipura virus',
 'chicken pox',
 'chickenp ox',
 'chickenpo x',
 'chickenpox',
 'chikecke npox',
 'chikungun ya',
 'chikunguny a',
 'chikungunya',
 'chikungunya & dengue',
 'chikungunya and dengue',
 'cholera',
 'complicate d malaria (plasmodiu m falciparum)',
 'crimean- congo haemorrhagi c fever',
 'crimean- congo haemorrhagic fever',
 'crimean- congo hemorrhagic fever',
 'dengue',
 'dengue & chikungunya',
 'dengue & leptospirosis',
 'dengue & malaria (p.vivax)',
 'dengue & scrub typhus',
 'diphtheria',
 'dysentery',
 'dysentry',
 'enteric fever',
 'fever',
 'fever of unknown origin',
 'fever with rash',
 'food poisioning',
 'food poisoning',
 'food poisoning (mushroom poisoning)',
 'hand foot and mouth disease',
 'hand, foot and mouth disease',
 'hand, foot, and mouth disease (hfmd)',
 'hepatitis a',
 'hepatitis a & e',
 'hepatitis a&e',
 'hepatitis b&c',
 'hepatitis e',
 'hfmd',
 'hmpv',
 'human rabies',
 'japanese encephalitis',
 'jaundice',
 'kyasanur forest disease',
 'leishmaniasis',
 'leptospiro sis',
 'leptospirosis',
 'malaria',
 'malaria (mixed)',
 'malaria (p. vivax & p.falciparu m)',
 'malaria (p. vivax & p.falciparum)',
 'malaria (p.falciparu m & p.vivax)',
 'malaria (p.falciparum & p. vivax) & dengue',
 'malaria (p.falciparum & p.vivax)',
 'malaria (p.falciparum )',
 'malaria (p.falciparum)',
 'malaria (p.vivax & p.falciparum)',
 'malaria (p.vivax)',
 'malaria (plasmodiu m vivax)',
 'malaria (plasmodium falciparum)',
 'measles',
 'measles and rubella',
 'meningitis',
 'meningococcal meningitis',
 'mixed malaria (plasmodiu m falciparum & plasmodiu m vivax)',
 'mpox',
 'mpox (clade i)',
 'mpox (clade ii)',
 'mpox (clade l)',
 'mumps',
 'nipah virus',
 'others',
 'paratyphoid',
 'pertussis',
 'rabies',
 'rubella',
 'scrub typhus',
 'scrub typhus and leptospirosis',
 'shigellosis',
 'suspecte d food poisoning',
 'suspected food poisoning (klebsiella)',
 'suspected food poisoning (mushroo m poisoning)',
 'suspected food poisoning (salmonella)',
 'suspected hepatitis',
 'suspected hfmd',
 'suspected measles',
 'suspected scrub typhus',
 'suspected typhoid',
 'typhoid',
 'typhoid & hepatitis e',
 'un differentiate d fever',
 'west nile fever']

In [ ]:
df['disease'] = (
    df['disease']
    .astype(str)
    .str.replace('\n',' ')
    .str.replace('\s+',' ', regex=True)
    .str.strip()
    .str.lower()
)

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_354/3463905788.py:5: SyntaxWarning: invalid escape sequence '\s'
  .str.replace('\s+',' ', regex=True)

In [ ]:
disease_fix = {
"acute gastroente ritis":"acute gastroenteritis",
"acute gastroenter itis":"acute gastroenteritis",
"acute gastroenteri tis":"acute gastroenteritis",
"acute gastroenterit is":"acute gastroenteritis",
"chikungun ya":"chikungunya",
"chikunguny a":"chikungunya",
"c hikungunya":"chikungunya",
"chicken pox":"chickenpox",
"chickenp ox":"chickenpox",
"chickenpo x":"chickenpox",
"leptospiro sis":"leptospirosis",
"food poisioning":"food poisoning",
"dysentry":"dysentery"
}

df['disease'] = df['disease'].replace(disease_fix)

In [ ]:
standard_disease = {
"acute diarrhoeal disease":"acute diarrheal disease",
"acute diarrheal diseases":"acute diarrheal disease",

"acute encephalitis syndrome":"acute encephalitic syndrome",

"hepatitis a":"hepatitis",
"hepatitis e":"hepatitis",
"hepatitis a&e":"hepatitis",
"hepatitis a & e":"hepatitis",

"malaria (p.vivax)":"malaria",
"malaria (plasmodium falciparum)":"malaria",
"malaria (p.falciparum)":"malaria",

"suspected food poisoning":"food poisoning",

"hfmd":"hand foot and mouth disease"
}

df['disease'] = df['disease'].replace(standard_disease)

In [ ]:
df['disease'] = df['disease'].str.replace('suspected ','')

In [ ]:
sorted(df['disease'].unique())

['acute diarrheal disease',
 'acute diarrheal disease (shigellosis)',
 'acute encephalitic syndrome',
 'acute encephalitic syndrome (chpv)',
 'acute gastroenterit is (norovirus)',
 'acute gastroenteriti s',
 'acute gastroenteritis',
 'acute hepatitis',
 'acute hepatitis a',
 'acute hepatitis e',
 'chandipura virus',
 'chickenpox',
 'chikecke npox',
 'chikungunya',
 'chikungunya & dengue',
 'chikungunya and dengue',
 'cholera',
 'complicate d malaria (plasmodiu m falciparum)',
 'crimean- congo haemorrhagi c fever',
 'crimean- congo haemorrhagic fever',
 'crimean- congo hemorrhagic fever',
 'dengue',
 'dengue & chikungunya',
 'dengue & leptospirosis',
 'dengue & malaria (p.vivax)',
 'dengue & scrub typhus',
 'diphtheria',
 'dysentery',
 'enteric fever',
 'fever',
 'fever of unknown origin',
 'fever with rash',
 'food poisoning',
 'food poisoning (klebsiella)',
 'food poisoning (mushroo m poisoning)',
 'food poisoning (mushroom poisoning)',
 'food poisoning (salmonella)',
 'hand foot and mouth disease',
 'hand, foot and mouth disease',
 'hand, foot, and mouth disease (hfmd)',
 'hepatitis',
 'hepatitis b&c',
 'hfmd',
 'hmpv',
 'human rabies',
 'japanese encephalitis',
 'jaundice',
 'kyasanur forest disease',
 'leishmaniasis',
 'leptospirosis',
 'malaria',
 'malaria (mixed)',
 'malaria (p. vivax & p.falciparu m)',
 'malaria (p. vivax & p.falciparum)',
 'malaria (p.falciparu m & p.vivax)',
 'malaria (p.falciparum & p. vivax) & dengue',
 'malaria (p.falciparum & p.vivax)',
 'malaria (p.falciparum )',
 'malaria (p.vivax & p.falciparum)',
 'malaria (plasmodiu m vivax)',
 'measles',
 'measles and rubella',
 'meningitis',
 'meningococcal meningitis',
 'mixed malaria (plasmodiu m falciparum & plasmodiu m vivax)',
 'mpox',
 'mpox (clade i)',
 'mpox (clade ii)',
 'mpox (clade l)',
 'mumps',
 'nipah virus',
 'others',
 'paratyphoid',
 'pertussis',
 'rabies',
 'rubella',
 'scrub typhus',
 'scrub typhus and leptospirosis',
 'shigellosis',
 'suspecte d food poisoning',
 'typhoid',
 'typhoid & hepatitis e',
 'un differentiate d fever',
 'west nile fever']

In [ ]:
disease_fix = {
"acute gastroenterit is":"acute gastroenteritis",
"acute gastroenteriti s":"acute gastroenteritis",
"complicate d malaria":"complicated malaria",
"plasmodiu m vivax":"plasmodium vivax",
"crimean- congo haemorrhagi c fever":"crimean-congo haemorrhagic fever",
"chikecke npox":"chickenpox",
"suspecte d food poisoning":"food poisoning",
"un differentiate d fever":"undifferentiated fever"
}

df['disease'] = df['disease'].replace(disease_fix)

In [ ]:
df['disease'] = df['disease'].str.replace(r"\(.*?\)", "", regex=True)
df['disease'] = df['disease'].str.strip()

In [ ]:
standard_disease = {
"acute hepatitis a":"hepatitis",
"acute hepatitis e":"hepatitis",

"hand, foot and mouth disease":"hand foot and mouth disease",
"hand, foot, and mouth disease":"hand foot and mouth disease",
"hfmd":"hand foot and mouth disease",

"measles and rubella":"measles",

"malaria (mixed)":"malaria",

"typhoid & hepatitis e":"typhoid"
}

df['disease'] = df['disease'].replace(standard_disease)

In [ ]:
df['disease'] = df['disease'].str.replace('suspected ', '')

In [ ]:
sorted(df['disease'].unique())

['acute diarrheal disease',
 'acute encephalitic syndrome',
 'acute gastroenterit is',
 'acute gastroenteritis',
 'acute hepatitis',
 'chandipura virus',
 'chickenpox',
 'chikungunya',
 'chikungunya & dengue',
 'chikungunya and dengue',
 'cholera',
 'complicate d malaria',
 'crimean- congo haemorrhagic fever',
 'crimean- congo hemorrhagic fever',
 'crimean-congo haemorrhagic fever',
 'dengue',
 'dengue & chikungunya',
 'dengue & leptospirosis',
 'dengue & malaria',
 'dengue & scrub typhus',
 'diphtheria',
 'dysentery',
 'enteric fever',
 'fever',
 'fever of unknown origin',
 'fever with rash',
 'food poisoning',
 'hand foot and mouth disease',
 'hepatitis',
 'hepatitis b&c',
 'hmpv',
 'human rabies',
 'japanese encephalitis',
 'jaundice',
 'kyasanur forest disease',
 'leishmaniasis',
 'leptospirosis',
 'malaria',
 'malaria  & dengue',
 'measles',
 'meningitis',
 'meningococcal meningitis',
 'mixed malaria',
 'mpox',
 'mumps',
 'nipah virus',
 'others',
 'paratyphoid',
 'pertussis',
 'rabies',
 'rubella',
 'scrub typhus',
 'scrub typhus and leptospirosis',
 'shigellosis',
 'typhoid',
 'undifferentiated fever',
 'west nile fever']

In [ ]:
disease_fix = {
"acute gastroenterit is":"acute gastroenteritis",
"complicate d malaria":"malaria"
}

df['disease'] = df['disease'].replace(disease_fix)

In [ ]:
standard_disease = {
"crimean- congo haemorrhagic fever":"crimean congo hemorrhagic fever",
"crimean- congo hemorrhagic fever":"crimean congo hemorrhagic fever",
"crimean-congo haemorrhagic fever":"crimean congo hemorrhagic fever",

"meningococcal meningitis":"meningitis",

"mixed malaria":"malaria",

"hepatitis b&c":"hepatitis",

"fever of unknown origin":"undifferentiated fever",
"fever with rash":"undifferentiated fever",
"fever":"undifferentiated fever"
}

df['disease'] = df['disease'].replace(standard_disease)

In [ ]:
df['disease'] = df['disease'].str.replace("chikungunya & dengue","dengue")
df['disease'] = df['disease'].str.replace("chikungunya and dengue","dengue")

df['disease'] = df['disease'].str.replace("dengue & chikungunya","dengue")
df['disease'] = df['disease'].str.replace("dengue & leptospirosis","dengue")
df['disease'] = df['disease'].str.replace("dengue & malaria","dengue")
df['disease'] = df['disease'].str.replace("dengue & scrub typhus","dengue")

df['disease'] = df['disease'].str.replace("scrub typhus and leptospirosis","scrub typhus")

In [ ]:
sorted(df['disease'].unique())

['acute diarrheal disease',
 'acute encephalitic syndrome',
 'acute gastroenteritis',
 'acute hepatitis',
 'chandipura virus',
 'chickenpox',
 'chikungunya',
 'cholera',
 'crimean congo hemorrhagic fever',
 'dengue',
 'diphtheria',
 'dysentery',
 'enteric fever',
 'food poisoning',
 'hand foot and mouth disease',
 'hepatitis',
 'hmpv',
 'human rabies',
 'japanese encephalitis',
 'jaundice',
 'kyasanur forest disease',
 'leishmaniasis',
 'leptospirosis',
 'malaria',
 'malaria  & dengue',
 'measles',
 'meningitis',
 'mpox',
 'mumps',
 'nipah virus',
 'others',
 'paratyphoid',
 'pertussis',
 'rabies',
 'rubella',
 'scrub typhus',
 'shigellosis',
 'typhoid',
 'undifferentiated fever',
 'west nile fever']

In [ ]:
df['disease'] = df['disease'].str.replace('malaria  & dengue','dengue')

In [ ]:
df['disease'] = df['disease'].replace({
"acute hepatitis":"hepatitis"
})

In [ ]:
df = df[df['disease'] != 'others']

In [ ]:
sorted(df['disease'].unique())
print("Total diseases:", df['disease'].nunique())

Total diseases: 37

In [ ]:
df['cases'] = pd.to_numeric(df['cases'], errors='coerce')
df['deaths'] = pd.to_numeric(df['deaths'], errors='coerce')

In [ ]:
df[['cases','deaths']].dtypes

cases     float64
deaths    float64
dtype: object

In [ ]:
df['cases'] = df['cases'].astype(int)
df['deaths'] = df['deaths'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
df[['cases','deaths']].isnull().sum()

cases     1256
deaths    1252
dtype: int64

In [ ]:
df[df['cases'].isnull()].head(10)

,state,district,disease,cases,deaths,start_date,report_date,status,comments
31,assam,lakhimpur,acute diarrheal disease,NaN,NaN,06-02-2025,Under \nSurveillance,cases reported from rangajan majgaon village u...,nan
32,bihar,patna,measles,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from phc daniyawan, villag...",nan
33,gujarat,tapi,food poisoning,NaN,NaN,06-02-2025,Under \nControl,cases were reported from a school under phc gu...,nan
34,jammu and kashmir,doda,human rabies,NaN,NaN,06-02-2025,Under \nSurveillance,"case was reported from sub-district: thathri, ...",nan
35,jammu and kashmir,kulgam,hepatitis,NaN,NaN,05-02-2025,Under \nSurveillance,cases of jaundice reported from village saidpo...,nan
36,jammu and kashmir,srinagar,hepatitis,NaN,NaN,06-02-2025,Under \nSurveillance,"cases of jaundice reported from gangbugh area,...",nan
37,jharkhand,deoghar,malaria,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from village: saruka, sub-...",nan
38,jharkhand,dhanbad,chickenpox,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from village: patrobad, su...",nan
39,jharkhand,dumka,measles,NaN,NaN,07-02-2025,Under \nSurveillance,cases were reported from dumka medical college...,nan
40,jharkhand,dumka,chickenpox,NaN,NaN,06-02-2025,Under \nSurveillance,"cases were reported from phc asansol, village:...",nan

In [ ]:
df[df['deaths'].isnull()].head(10)

,state,district,disease,cases,deaths,start_date,report_date,status,comments
31,assam,lakhimpur,acute diarrheal disease,NaN,NaN,06-02-2025,Under \nSurveillance,cases reported from rangajan majgaon village u...,nan
32,bihar,patna,measles,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from phc daniyawan, villag...",nan
33,gujarat,tapi,food poisoning,NaN,NaN,06-02-2025,Under \nControl,cases were reported from a school under phc gu...,nan
34,jammu and kashmir,doda,human rabies,NaN,NaN,06-02-2025,Under \nSurveillance,"case was reported from sub-district: thathri, ...",nan
35,jammu and kashmir,kulgam,hepatitis,NaN,NaN,05-02-2025,Under \nSurveillance,cases of jaundice reported from village saidpo...,nan
36,jammu and kashmir,srinagar,hepatitis,NaN,NaN,06-02-2025,Under \nSurveillance,"cases of jaundice reported from gangbugh area,...",nan
37,jharkhand,deoghar,malaria,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from village: saruka, sub-...",nan
38,jharkhand,dhanbad,chickenpox,NaN,NaN,07-02-2025,Under \nSurveillance,"cases were reported from village: patrobad, su...",nan
39,jharkhand,dumka,measles,NaN,NaN,07-02-2025,Under \nSurveillance,cases were reported from dumka medical college...,nan
40,jharkhand,dumka,chickenpox,NaN,NaN,06-02-2025,Under \nSurveillance,"cases were reported from phc asansol, village:...",nan

In [ ]:
df['cases'] = df['cases'].fillna(0)
df['deaths'] = df['deaths'].fillna(0)

df['cases'] = df['cases'].astype(int)
df['deaths'] = df['deaths'].astype(int)

In [ ]:
df[['cases','deaths']].isnull().sum()

cases     0
deaths    0
dtype: int64

In [ ]:
df.shape

(2301, 9)

In [ ]:
df.columns

Index(['state', 'district', 'disease', 'cases', 'deaths', 'start_date',
       'report_date', 'status', 'comments'],
      dtype='object')

In [ ]:
df['state'].nunique()

33

In [ ]:
df['district'].nunique()

508

In [ ]:
df.isnull().sum()

state          0
district       0
disease        0
cases          0
deaths         0
start_date     0
report_date    0
status         0
comments       0
dtype: int64

In [ ]:
df[['start_date','report_date']].head(10)

      start_date   report_date
1   27-09-\n2025  04-10-\n2025
2   26-09-\n2025  03-10-\n2025
3   29-09-\n2025  01-10-\n2025
4   30-09-\n2025  30-09-\n2025
5   28-09-\n2025  29-09-\n2025
6   30-09-\n2025  30-09-\n2025
7   30-09-\n2025  03-10-\n2025
8   01-10-\n2025  03-10-\n2025
9   30-09-\n2025  01-10-\n2025
10  01-10-\n2025  01-10-\n2025

In [ ]:
df['start_date'] = df['start_date'].astype(str).str.replace('\n','')
df['report_date'] = df['report_date'].astype(str).str.replace('\n','')

In [ ]:
df['start_date'] = pd.to_datetime(df['start_date'], format='%d-%m-%Y', errors='coerce')
df['report_date'] = pd.to_datetime(df['report_date'], format='%d-%m-%Y', errors='coerce')

In [ ]:
df[['start_date','report_date']].head()

  start_date report_date
1 2025-09-27  2025-10-04
2 2025-09-26  2025-10-03
3 2025-09-29  2025-10-01
4 2025-09-30  2025-09-30
5 2025-09-28  2025-09-29

In [ ]:
df[['start_date','report_date']].isnull().sum()

start_date      208
report_date    1425
dtype: int64

In [ ]:
df['start_date'] = df['start_date'].fillna(df['report_date'])

In [ ]:
df['report_date'] = df['report_date'].fillna(df['start_date'])

In [ ]:
df[['start_date','report_date']].isnull().sum()

start_date     208
report_date    208
dtype: int64

In [ ]:
df['year'] = df['start_date'].dt.year
df['month'] = df['start_date'].dt.month
df['week'] = df['start_date'].dt.isocalendar().week

In [ ]:
df[df['start_date'].isnull()].head(10)

,state,district,disease,cases,deaths,start_date,report_date,status,comments,year,month,week
76,bihar,purbichamparan,measles,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
77,kerala,wayanad,acute diarrheal disease,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
78,madhya pradesh,bhopal,hepatitis,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
79,tamil nadu,krishnagiri,acute diarrheal disease,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
200,andhra pradesh,kakinada,food poisoning,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
201,assam,bongaigaon,japanese encephalitis,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
202,kerala,kannur,dengue,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
322,bihar,munger,undifferentiated fever,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
323,karnataka,bagalkot,chickenpox,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>
324,kerala,alappuzha,mpox,0,0,NaT,NaT,nan,nan,NaN,NaN,<NA>

In [ ]:
df = df[~(
    (df['cases'] == 0) &
    (df['deaths'] == 0) &
    (df['start_date'].isna()) &
    (df['report_date'].isna())
)]

In [ ]:
df.shape

(2134, 12)

In [ ]:
df.isnull().sum()

state           0
district        0
disease         0
cases           0
deaths          0
start_date     41
report_date    41
status          0
comments        0
year           41
month          41
week           41
dtype: int64

In [ ]:
df = df.dropna(subset=['start_date','report_date'])

In [ ]:
df.isnull().sum()

state          0
district       0
disease        0
cases          0
deaths         0
start_date     0
report_date    0
status         0
comments       0
year           0
month          0
week           0
dtype: int64

In [ ]:
df.shape

(2093, 12)

In [ ]:
district_stats = df.groupby(['state','district']).agg(
    outbreak_count=('disease','count'),
    total_cases=('cases','sum'),
    total_deaths=('deaths','sum')
).reset_index()

In [ ]:
top_disease = (
    df.groupby(['state','district','disease'])['cases']
    .sum()
    .reset_index()
    .sort_values(['state','district','cases'],ascending=[True,True,False])
)

top_disease = top_disease.groupby(['state','district']).first().reset_index()

In [ ]:
master = district_stats.merge(
    top_disease[['state','district','disease']],
    on=['state','district']
)

master.rename(columns={'disease':'top_disease'}, inplace=True)

In [ ]:
df

,state,district,disease,cases,deaths,start_date,report_date,status,comments,year,month,week
1,bihar,aurangabad,acute diarrheal disease,11,0,2025-09-27,2025-10-04,under surveillance,Cases of loose stools and vomiting were report...,2025.0,9.0,39
2,bihar,aurangabad,acute diarrheal disease,19,0,2025-09-26,2025-10-03,under surveillance,Cases of loose stools and vomiting were report...,2025.0,9.0,39
3,chhattisgarh,bastar,leptospirosis,5,0,2025-09-29,2025-10-01,under control,"Cases were reported from Villages Dabaguda, Ma...",2025.0,9.0,40
4,gujarat,chhotaudepur,food poisoning,7,0,2025-09-30,2025-09-30,under control,Cases presenting with vomiting and weakness we...,2025.0,9.0,40
5,gujarat,panchmahal,food poisoning,63,0,2025-09-28,2025-09-29,under surveillance,Cases of vomiting and loose stools were report...,2025.0,9.0,39
...,...,...,...,...,...,...,...,...,...,...,...,...
2918,mizoram,saitual,typhoid,22,0,2025-07-27,2025-07-27,"cases of fever, abdominal pain and vomiting we...",nan,2025.0,7.0,30
2919,odisha,gajapati,chikungunya,78,0,2025-08-18,2025-08-18,"cases were reported from village kitingi, sub-...",nan,2025.0,8.0,34
2920,rajasthan,jaipur,hepatitis,20,0,2025-08-11,2025-08-11,"cases of loose motion, vomiting, loss of appet...",nan,2025.0,8.0,33
2921,rajasthan,udaipur,undifferentiated fever,359,0,2025-08-09,2025-08-09,cases of fever were reported from village lamb...,nan,2025.0,8.0,32
2922,uttar pradesh,jhansi,acute diarrheal disease,16,0,2025-07-27,2025-07-27,cases of loose motion and vomiting were report...,nan,2025.0,7.0,30

In [ ]:
df['year'] = df['year'].astype(int)
df['month'] = df['month'].astype(int)
df['week'] = df['week'].astype(int)

In [ ]:
district_stats = df.groupby(['state','district']).agg(
    outbreak_count=('disease','count'),
    total_cases=('cases','sum'),
    total_deaths=('deaths','sum')
).reset_index()

In [ ]:
top_disease = (
    df.groupby(['state','district','disease'])['cases']
    .sum()
    .reset_index()
    .sort_values(['state','district','cases'], ascending=[True,True,False])
)

top_disease = top_disease.groupby(['state','district']).first().reset_index()

In [ ]:
master = district_stats.merge(
    top_disease[['state','district','disease']],
    on=['state','district']
)

master.rename(columns={'disease':'top_disease'}, inplace=True)

In [ ]:
df

,state,district,disease,cases,deaths,start_date,report_date,status,comments,year,month,week
1,bihar,aurangabad,acute diarrheal disease,11,0,2025-09-27,2025-10-04,under surveillance,Cases of loose stools and vomiting were report...,2025,9,39
2,bihar,aurangabad,acute diarrheal disease,19,0,2025-09-26,2025-10-03,under surveillance,Cases of loose stools and vomiting were report...,2025,9,39
3,chhattisgarh,bastar,leptospirosis,5,0,2025-09-29,2025-10-01,under control,"Cases were reported from Villages Dabaguda, Ma...",2025,9,40
4,gujarat,chhotaudepur,food poisoning,7,0,2025-09-30,2025-09-30,under control,Cases presenting with vomiting and weakness we...,2025,9,40
5,gujarat,panchmahal,food poisoning,63,0,2025-09-28,2025-09-29,under surveillance,Cases of vomiting and loose stools were report...,2025,9,39
...,...,...,...,...,...,...,...,...,...,...,...,...
2918,mizoram,saitual,typhoid,22,0,2025-07-27,2025-07-27,"cases of fever, abdominal pain and vomiting we...",nan,2025,7,30
2919,odisha,gajapati,chikungunya,78,0,2025-08-18,2025-08-18,"cases were reported from village kitingi, sub-...",nan,2025,8,34
2920,rajasthan,jaipur,hepatitis,20,0,2025-08-11,2025-08-11,"cases of loose motion, vomiting, loss of appet...",nan,2025,8,33
2921,rajasthan,udaipur,undifferentiated fever,359,0,2025-08-09,2025-08-09,cases of fever were reported from village lamb...,nan,2025,8,32
2922,uttar pradesh,jhansi,acute diarrheal disease,16,0,2025-07-27,2025-07-27,cases of loose motion and vomiting were report...,nan,2025,7,30

In [ ]:
mask = df['comments'].isna() & df['status'].str.contains('case', case=False, na=False)
df.loc[mask, 'comments'] = df.loc[mask, 'status']

In [ ]:
df['status'] = df['status'].str.lower().str.strip()

In [ ]:
df.isnull().sum()

state          0
district       0
disease        0
cases          0
deaths         0
start_date     0
report_date    0
status         0
comments       0
year           0
month          0
week           0
dtype: int64

In [ ]:
df['start_date'].dtype

dtype('<M8[ns]')

In [ ]:
df = df.sort_values(by='start_date', ascending=False)
df = df.reset_index(drop=True)

In [ ]:
df[['start_date','state','district','disease']].head(10)

  start_date              state        district                  disease
0 2026-01-31             kerala       ernakulam                hepatitis
1 2026-01-31             kerala       kozhikode           food poisoning
2 2026-01-31             kerala       kozhikode               chickenpox
3 2026-01-30          telangana        suryapet  acute diarrheal disease
4 2026-01-30             kerala          idukki                hepatitis
5 2026-01-30        maharashtra       dharashiv                  measles
6 2026-01-30             kerala        palakkad               chickenpox
7 2026-01-29              bihar       begusarai                  measles
8 2026-01-29  jammu and kashmir       baramulla               chickenpox
9 2026-01-29        west bengal  purbabardhaman           food poisoning

In [ ]:
df = df.sort_values(by=['year','week'], ascending=False)
df = df.reset_index(drop=True)

In [ ]:
df.to_csv("outbreak_dataset_clean_sorted.csv", index=False)

#geocode_health_centre

In [ ]:
import pandas as pd

geo = pd.read_csv("geocode_health_centre.csv", low_memory=False)

geo.shape

(200438, 13)

In [ ]:
out = pd.read_csv("/content/outbreak_dataset_clean_sorted.csv")

In [ ]:
out.head()

,state,district,disease,cases,deaths,start_date,report_date,status,comments,year,month,week
0,kerala,ernakulam,hepatitis,22,0,2026-01-31,2026-01-31,under surveillance,"Cases of nausea, abdominal pain and fever were...",2026,1,5
1,kerala,kozhikode,food poisoning,182,0,2026-01-31,2026-01-31,under surveillance,Cases of loose watery stools were reported fro...,2026,1,5
2,kerala,kozhikode,chickenpox,30,0,2026-01-31,2026-01-31,under surveillance,Cases of fever with vesicular rash were report...,2026,1,5
3,telangana,suryapet,acute diarrheal disease,104,0,2026-01-30,2026-01-30,under surveillance,Cases of loose motion were reported from Villa...,2026,1,5
4,kerala,idukki,hepatitis,22,0,2026-01-30,2026-01-31,under surveillance,"Cases of nausea, abdominal pain and yellow col...",2026,1,5

In [ ]:
out['state'].unique()

array(['kerala', 'telangana', 'maharashtra', 'bihar', 'jammu and kashmir',
       'west bengal', 'madhya pradesh', 'odisha', 'tamil nadu',
       'uttarakhand', 'gujarat', 'assam', 'andhra pradesh',
       'uttar pradesh', 'chhattisgarh', 'karnataka', 'jharkhand',
       'himachal pradesh', 'delhi', 'punjab', 'arunachal pradesh',
       'andaman & nicobar islands', 'nagaland', 'haryana', 'meghalaya',
       'rajasthan', 'manipur', 'mizoram', 'sikkim', 'goa', 'ladakh',
       'puducherry', 'tripura'], dtype=object)

In [ ]:
out['district'].unique()

array(['ernakulam', 'kozhikode', 'suryapet', 'idukki', 'dharashiv',
       'palakkad', 'begusarai', 'baramulla', 'purbabardhaman',
       'eastnimar', 'umaria', 'gwalior', 'purnia', 'gadchiroli',
       'jharsuguda', 'perambalur', 'chamoli', 'ganjam', 'bhavnagar',
       'kottayam', 'dewas', 'thiruvananthapuram', 'kamrup', 'coimbatore',
       'prakasam', 'thrissur', 'nabarangpur', 'farrukhabad',
       'ananthapuramu', 'rajkot', 'panchmahal', 'villupuram',
       'ashoknagar', 'rajnandgaon', 'raigarh', 'ahmedabad', 'lucknow',
       'hassan', 'westsinghbhum', 'janjgir- champa', 'kannur', 'bidar',
       'mayiladuthurai', 'katihar', 'morena', 'purbichamparan',
       'namakkal', 'jamtara', 'gadag', 'latehar', 'thane', 'sundargarh',
       'mandi', 'ghaziabad', 'biswanath', 'salem', 'malappuram',
       '24paraganasnorth', 'narsinghpur', 'kalahandi', 'burhanpur',
       'southeast', 'kendujhar', 'nanded', 'alipurduar', 'ludhiana',
       'papumpare', 'pudukkottai', 'chandrapur', 'kokrajhar',
       'gautambuddhanagar', 'jamnagar', 'kendrapara', 'jorhat', 'jammu',
       'hamirpur', 'rupnagar', 'gandhinagar', 'navsari', 'balodabazar',
       'satara', 'jagatsinghapur', 'nagpur', 'wayanad', 'tenkasi',
       'visakhapatnam', 'koppal', 'datia', 'khordha', 'howrah', 'jhabua',
       'narmada', 'balod', 'srisathyasai', 'anand', 'southandamans',
       'shivpuri', 'mahesana', 'nicobars', 'thiruvallur', 'jehanabad',
       'surat', 'mandsaur', 'mayurbhanj', 'haveri', 'longleng', 'boudh',
       'bharuch', 'damoh', 'hooghly', 'kishanganj', 'tirunelveli',
       'bhagalpur', 'thenilgiris', 'koraput', 'alirajpur',
       'east singhbhum', 'gurugram', 'rajgarh', 'sonitpur', 'yadgir',
       'tirupathur', 'bhadrak', 'kasaragod', 'kollam', 'sabarkantha',
       'chhatarpur', 'pathanamthitta', 'dumka', 'dhule', 'darrang',
       'raipur', 'guntur', 'gaya', 'jabalpur', 'ariyalur',
       'bengaluruurban', 'mon', 'eastjaintiahills', 'chhotaudepur',
       'raigad', 'kushinagar', 'sehore', 'kupwara', 'erode',
       'janjgirchampa', 'giridih', 'kanker', 'dhemaji', 'tiruvannamalai',
       'sivaganga', 'kulgam', 'srinagar', 'nayagarh', 'panipat',
       'jaunpur', 'ajmer', 'amravati', 'sambhal', 'cuttack',
       'allurisitharamaraju', 'agarmalwa', 'tamenglong', 'jhansi',
       'westsiang', 'saiha', 'saraikela kharsawan', 'khargone', 'kurnool',
       'lawngtlai', 'ujjain', 'tiruchirappalli', 'kolhapur', 'neemuch',
       'ukhrul', 'rayagada', 'meerut', 'munger', 'shivamogga', 'pulwama',
       'kathua', 'jhargram', 'banka', 'palnadu', 'cuddalore', 'belagavi',
       'akola', 'pune', 'khairgarhchhuikhadangandai', 'jalgaon',
       'kallakurichi', 'raichur', 'supaul', 'bhandara', 'palghar',
       'aurangabad', 'kanniyakumari', 'sindhudurg', 'balangir',
       'singrauli', 'imphalwest', 'gangtok', 'solapur', 'fatehpur',
       'ratlam', 'chittoor', 'sheopur', 'surendranagar', 'kandhamal',
       'amethi', 'southwestgarohills', 'southgoa', 'coochbehar',
       'purulia', 'prayagraj', 'panna', 'narayanpur', 'barwani',
       'vellore', 'noklak', 'parvathipurammanyam', 'barpeta', 'hardoi',
       'parbhani', 'bilaspur', 'una', 'kamjong', 'pilibhit', 'satna',
       'washim', 'sonipat', 'bastar', 'yamunanagar', 'sonepur',
       'sonbhadra', 'hapur', 'buldhana', 'garhwa', 'chandauli', 'deoghar',
       'lehladakh', 'dhanbad', 'pashchimchamparan', 'jashpur', 'bhojpur',
       'madhubani', 'bargarh', 'durg', 'mirzapur', 'tirap', 'deogarh',
       'kurukshetra', 'rewa', 'korea', 'hazaribagh', 'sas nagar',
       'siddharthnagar', 'northwest', 'pondicherry', 'aizawl', 'kangra',
       'patan', 'vadodara', 'gopalganj', 'vaishali', 'bandipora',
       'alappuzha', 'northtripura', 'darbhanga', 'changlang',
       'chitradurga', 'southwest', 'lakhimpur', 'ribhoi', 'malkangiri',
       'katni', 'hojai', 'mandla', 'guna', 'birbhum', 'majuli',
       'spsrnellore', 'ntr', 'indore', 'mahe', 'baran', 'bajali',
       'ganderbal', 'rampur', 'y.s.r.', 'dharwad', 'yavatmal',
       'mahasamund', 'sidhi', 'gaurellapendramarwahi', 'shopian',
       'nandurbar', 'kheda', 'kota', 'kanchipuram', 'shajapur', 'eluru',
       'sahebganj', 'tirupati', 'karnal', 'hoshangabad', 'anantnag',
       'dhubri', 'westjaintiahills', 'chhatrapati sambhajinagar',
       'mandya', 'charaideo', 'kamrupmetro', 'jalandhar',
       'southwestkhasihills', 'tinsukia', 'eastkhasihills', 'dibrugarh',
       'maldah', 'westtripura', 'hailakandi', 'tumakuru', 'nagaon',
       'bhind', 'shahdol', 'lalitpur', 'raisen', 'gajapati', 'vidisha',
       'palamu', 'ballari', 'rajsamand', 'mungeli', 'longding', 'kolar',
       'dindori', 'jaipur', 'sambalpur', 'aligarh', 'amritsar', 'udaipur',
       'pratapgarh', 'panchkula', 'thanjavur', 'girsomnath', 'jhalawar',
       'krishnagiri', 'vijayapura', 'anantapur', 'lowersubansiri',
       'manendragarhchirimiribharatpur', 'bhopal', 'namsai', 'soreng',
       'tamulpur', 'senapati', 'valsad', 'betul', 'saitual', 'mathura',
       'bokaro', 'chikballapur', 'banaskantha', 'jhunjhunu', 'nuapada',
       'lohit', 'easternwestkhasihills', 'balaghat', 'bankura', 'dimapur',
       'tikamgarh', 'patiala', 'patna', 'janjgir-champa', 'seoni',
       'cachar', 'chikkamagaluru', 'samastipur', 'bongaigaon', 'karaikal',
       'almora', 'eastgarohills', 'kaithal', 'mohlamanpurambagarhchouki',
       'lohardaga', 'saharanpur', 'southgarohills', 'bemetara', 'dohad',
       'northgoa', 'badgam', 'bagalkot', 'simdega', 'golaghat', 'rajauri',
       'dhar', 'devbhumidwarka', 'nalbari', 'raebareli', 'anugul',
       'gumla', 'kalaburagi', 'kolasib', 'vijayanagar', 'anakapalli',
       'puri', 'karimganj', 'jalpaiguri', 'virudhunagar', 'doda',
       'jajapur', 'murshidabad', 'udamsinghnagar', 'gyalshing',
       'hyderabad', 'goalpara', 'kargil', 'dang', 'mahisagar', 'khunti',
       'dakshinkannad', 'medinipurwest', 'beed', 'junagadh',
       'northgarohills', 'udupi', 'mysuru', 'pakkekessang', 'saran',
       'morbi', '24paraganassouth', 'koderma', 'godda', 'arvalli',
       'kakinada', 'northandmiddleandaman', 'basti', 'dholpur', 'theni',
       'mumbaisuburban', 'nuh', 'surguja', 'niwari', 'dehradun', 'gondia',
       'haridwar', 'dharmapuri', 'dindigul', 'ranchi', 'sitamarhi',
       'westkhasihills', 'davangere', 'medinipureast', 'ranipet',
       'southtripura', 'paschimbardhaman', 'jalore', 'srimuktsarsahib',
       'dantewada', 'latur', 'nandyal', 'ramanathapuram', 'kachchh',
       'konaseema', 'chirang', 'udalguri', 'dhamtari', 'amreli', 'nadia',
       'sangli', 'uttarkannad', 'kabirdham', 'nandamuritarakaramarao',
       'westgarohills', 'madhepura', 'karur', 'dimahasao', 'kondagaon',
       'muzaffarnagar', 'ambedkarnagar', 'moradabad', 'wardha', 'tapi',
       'madurai', 'tuticorin', 'faridkot', 'bharatpur', 'chatra',
       'dhenkanal', 'udhampur', 'shravasti', 'poonch'], dtype=object)

In [ ]:
geo.head()

,State Name,District Name,Subdistrict Name,Facility Type,Facility Name,Facility Address,Latitude,Longitude,ActiveFlag_C,NOTIONAL_PHYSICAL,Location Type,Type Of Facility,Nin_N
0,A & N Islands,Nicobar,Nancowry,chc,CHC Nancowry,Kamorta,7.96109,93.5589,Y,Physical,Rural,Public,NaN
1,A & N Islands,South Andaman,Ferrargunj,chc,CHC Bambooflat,NaN,11.7303,92.65003,Y,Physical,Rural,Public,NaN
2,A & N Islands,North and Middle Andaman,Rangat,chc,CHC Rangat,NaN,12.71609,92.90579,Y,Physical,Rural,Public,NaN
3,A & N Islands,North and Middle Andaman,Diglipur,chc,CHC Diglipur,NaN,13.30682,92.9411,Y,Physical,Rural,Public,NaN
4,A & N Islands,Nicobar,Car Nicobar,dis_h,BJR Hospital,NaN,9.14893,92.75578,Y,Physical,Rural,Public,NaN

In [ ]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [ ]:
df["state_name"] = df["state_name"].str.lower().str.strip()
df["district_name"] = df["district_name"].str.lower().str.strip()
df["subdistrict_name"] = df["subdistrict_name"].str.lower().str.strip()

In [ ]:
df.columns

Index(['state_name', 'district_name', 'subdistrict_name', 'facility_type',
       'facility_name', 'facility_address', 'latitude', 'longitude',
       'activeflag_c', 'notional_physical', 'location_type',
       'type_of_facility', 'nin_n'],
      dtype='object')

In [ ]:
df["state_name"].unique()

array(['a & n islands', 'andhra pradesh', 'andhra pradesh old',
       'arunachal pradesh', 'assam', 'bihar', 'chandigarh',
       'chhattisgarh', 'dadra & nagar haveli', 'daman & diu', 'delhi',
       'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jammu & kashmir',
       'jharkhand', 'karnataka', 'kerala', 'lakshadweep',
       'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram',
       'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan',
       'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh',
       'uttarakhand', 'west bengal'], dtype=object)

In [ ]:
df["district_name"].nunique()

668

In [ ]:
state_mapping = {
    "a & n islands": "andaman and nicobar islands",
    "andhra pradesh old": "andhra pradesh",
    "jammu & kashmir": "jammu and kashmir",
    "dadra & nagar haveli": "dadra and nagar haveli and daman and diu",
    "daman & diu": "dadra and nagar haveli and daman and diu"
}

df["state_name"] = df["state_name"].replace(state_mapping)

In [ ]:
df["state_name"].unique()

array(['andaman and nicobar islands', 'andhra pradesh',
       'arunachal pradesh', 'assam', 'bihar', 'chandigarh',
       'chhattisgarh', 'dadra and nagar haveli and daman and diu',
       'delhi', 'goa', 'gujarat', 'haryana', 'himachal pradesh',
       'jammu and kashmir', 'jharkhand', 'karnataka', 'kerala',
       'lakshadweep', 'madhya pradesh', 'maharashtra', 'manipur',
       'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry',
       'punjab', 'rajasthan', 'sikkim', 'tamil nadu', 'telangana',
       'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal'],
      dtype=object)

In [ ]:
df["district_name"] = df["district_name"].str.lower().str.strip()

In [ ]:
df["district_name"].nunique()

668

In [ ]:
df["district_name"] = df["district_name"].str.replace("  ", " ")

In [ ]:
df["district_name"] = df["district_name"].str.replace("-", " ")

In [ ]:
df["district_name"] = df["district_name"].str.strip()

In [ ]:
df['district_name'].unique()

array(['nicobar', 'south andaman', 'north and middle andaman', 'chittoor',
       'nellore', 'anantapur', 'cuddapah', 'prakasam', 'kurnool',
       'krishna', 'guntur', 'west godavari', 'east godavari',
       'vishakapatnam', 'vizianagaram', 'srikakulam', 'nalgonda',
       'ranga reddy', 'medak', 'mahbubnagar', 'khammam', 'hyderabad',
       'warangal', 'nizamabad', 'karim nagar', 'adilabad', 'longding',
       'west kameng', 'papum pare', 'east kameng', 'tirap', 'changlang',
       'tawang', 'lower subansiri', 'west siang', 'kra daadi',
       'kurung kumey', 'east siang', 'anjaw', 'lower dibang valley',
       'lohit', 'namsai', 'siang', 'upper subansiri', 'upper siang',
       'dibang valley', 'hailakandi', 'karimganj', 'cachar', 'dima hasao',
       'dhubri', 'nagaon', 'kamrup r', 'goalpara', 'karbi anglong',
       'kamrup m', 'golaghat', 'nalbari', 'darrang', 'barpeta',
       'marigaon', 'bongaigaon', 'jorhat', 'kokrajhar', 'chirang',
       'baksa', 'udalguri', 'sonitpur', 'sibsagar', 'lakhimpur',
       'dibrugarh', 'tinsukia', 'dhemaji', 'rohtas', 'jamui',
       'aurangabad', 'kaimur bhabua', 'banka', 'nawada', 'nalanda',
       'jehanabad', 'sheikhpura', 'bhagalpur', 'lakhisarai', 'patna',
       'begusarai', 'bhojpur', 'khagaria', 'katihar', 'vaishali',
       'purnia', 'samastipur', 'siwan', 'saran', 'muzaffarpur', 'araria',
       'darbhanga', 'supaul', 'kishanganj', 'madhubani', 'gopalganj',
       'east champaran', 'gaya', 'arwal', 'munger', 'buxar', 'saharsa',
       'madhepura', 'sitamarhi', 'west champaran', 'sheohar',
       'chandigarh', 'sukma', 'bijapur', 'dantewada', 'bastar',
       'narayanpur', 'kondagaon', 'gariyaband', 'kanker', 'dhamtari',
       'rajnandgaon', 'balod', 'raipur', 'durg', 'mahasamund', 'bemetra',
       'baloda bazar', 'raigarh', 'janjgir champa', 'kawardha',
       'bilaspur', 'mungeli', 'korba', 'jashpur', 'surguja', 'surajpur',
       'koriya', 'balrampur', 'dadra and nagar haveli', 'daman', 'diu',
       'south east', 'new delhi', 'east', 'south west', 'west', 'central',
       'shahdara', 'north east', 'north west', 'north', 'south',
       'south goa', 'north goa', 'valsad', 'the dangs', 'navsari',
       'gir somnath', 'surat', 'amreli', 'tapi', 'junagadh', 'bhavnagar',
       'porbandar', 'narmada', 'bharuch', 'rajkot', 'botad', 'jamnagar',
       'devbhumi dwarka', 'vadodara', 'chhotaudepur', 'anand',
       'panch mahals', 'ahmedabad', 'surendranagar', 'kheda', 'dahod',
       'morbi', 'kachchh', 'mahisagar', 'aravalli', 'mahesana',
       'gandhinagar', 'sabar kantha', 'patan', 'banas kantha', 'mewat',
       'mahendragarh', 'palwal', 'rewari', 'gurgaon', 'faridabad',
       'rohtak', 'jhajjar', 'bhiwani', 'sonipat', 'hisar', 'jind',
       'panipat', 'fatehabad', 'sirsa', 'karnal', 'kaithal',
       'kurukshetra', 'yamunanagar', 'ambala', 'panchkula', 'sirmaur',
       'shimla', 'solan', 'una', 'kullu', 'mandi', 'kinnaur', 'hamirpur',
       'kangra', 'lahul spiti', 'chamba', 'kathua', 'samba', 'jammu',
       'udhampur', 'doda', 'reasi', 'rajouri', 'ramban', 'kargil',
       'badgam', 'anantnag', 'kulgam', 'poonch', 'kishtwar', 'shopian',
       'pulwama', 'baramula', 'srinagar', 'bandipora', 'ganderbal',
       'leh ladakh', 'kupwara', 'pashchimi singhbhum', 'purbi singhbhum',
       'simdega', 'saraikela', 'khunti', 'gumla', 'ranchi', 'latehar',
       'lohardaga', 'ramgarh', 'bokaro', 'dhanbad', 'garhwa',
       'hazaribagh', 'chatra', 'jamtara', 'giridih', 'palamu', 'dumka',
       'deoghar', 'kodarma', 'pakaur', 'godda', 'sahibganj',
       'chamrajnagar', 'kodagu', 'mysore', 'mandya', 'ramanagar',
       'hassan', 'dakshina kannada', 'bangalore urban', 'tumkur', 'kolar',
       'udupi', 'bangalore rural', 'chikmagalur', 'chikkaballapur',
       'chitradurga', 'shimoga', 'uttara kannada', 'davanagere', 'haveri',
       'bellary', 'gadag', 'koppal', 'belgaum', 'bagalkote', 'raichur',
       'yadgir', 'gulbarga', 'bidar', 'dharwad', 'thiruvananthapuram',
       'kollam', 'pathanamthitta', 'alappuzha', 'kottayam', 'idukki',
       'ernakulam', 'thrissur', 'palakkad', 'malappuram', 'kozhikkode',
       'wayanad', 'kannur', 'kasaragod', 'lakshadweep', 'burhanpur',
       'barwani', 'balaghat', 'khargone', 'betul', 'khandwa',
       'chhindwada', 'seoni', 'dhar', 'alirajpur', 'harda', 'indore',
       'hoshangabad', 'mandla', 'dewas', 'jhabua', 'dindori', 'sehore',
       'narsinghpur', 'anuppur', 'raisen', 'ujjain', 'shahdol', 'bhopal',
       'shajapur', 'jabalpur', 'ratlam', 'umaria', 'damoh', 'sagar',
       'katni', 'rajgarh', 'vidisha', 'agar malwa', 'mandsaur', 'sidhi',
       'panna', 'singroli', 'satna', 'guna', 'chhatarpur', 'neemuch',
       'rewa', 'ashok nagar', 'tikamgarh', 'shivpuri', 'datia', 'sheopur',
       'gwalior', 'morena', 'bhind', 'sindhudurg', 'kolhapur',
       'ratnagiri', 'sangli', 'satara', 'solapur', 'osmanabad',
       'chandrapur', 'latur', 'amravati', 'pune', 'gondiya', 'bid',
       'ahmednagar', 'nanded', 'gadchiroli', 'brihan mumbai', 'parbhani',
       'thane', 'palghar', 'hingoli', 'jalna', 'nashik', 'yavatmal',
       'buldana', 'washim', 'jalgaon', 'akola', 'wardha', 'nagpur',
       'dhule', 'bhandara', 'nandurbar', 'chandel', 'churachandpur',
       'thoubal', 'bishnupur', 'imphal west', 'tamenglong', 'imphal east',
       'ukhrul', 'senapati', 'east khasi hills', 'west jaintia hills',
       'south west khasi hills', 'west garo hills',
       'south west garo hills', 'south garo hills', 'east jaintia hills',
       'west khasi hills', 'ri bhoi', 'north garo hills',
       'east garo hills', 'lawngtlai', 'lunglei', 'champhai', 'serchhip',
       'aizawl west', 'aizawl east', 'kolasib', 'saiha', 'mamit', 'peren',
       'phek', 'kohima', 'kiphire', 'dimapur', 'zunheboto', 'tuensang',
       'wokha', 'mon', 'mokokchung', 'longleng', 'malkangiri', 'koraput',
       'gajapati', 'rayagada', 'ganjam', 'nabarangapur', 'kalahandi',
       'puri', 'khordha', 'kandhamal', 'nayagarh', 'nuapada',
       'jagatsinghpur', 'cuttack', 'balangir', 'kendrapara', 'baudh',
       'dhenkanal', 'jajapur', 'sonapur', 'anugul', 'bhadrak', 'bargarh',
       'keonjhar', 'sambalpur', 'baleshwar', 'deogarh', 'mayurbhanj',
       'sundargarh', 'jharsuguda', 'karaikal', 'mahe', 'pondicherry',
       'yanam', 'mansa', 'patiala', 'sangrur', 'bathinda', 'fazilka',
       'muktsar', 'barnala', 'mohali sas nagar', 'faridkot',
       'fatehgarh sahib', 'moga', 'ludhiana', 'firozpur', 'rupnagar',
       'nawanshahr', 'jalandhar', 'tarn taran', 'pathankot', 'hoshiarpur',
       'kapurthala', 'amritsar', 'gurdaspur', 'banswara', 'dungarpur',
       'pratapgarh', 'jhalawar', 'udaipur', 'chittaurgarh', 'baran',
       'sirohi', 'kota', 'jalor', 'rajsamand', 'barmer', 'pali',
       'bhilwara', 'sikar', 'bundi', 'ajmer', 'tonk', 'sawai madhopur',
       'jodhpur', 'karauli', 'jaisalmer', 'dhaulpur', 'dausa',
       'bharatpur', 'jaipur', 'nagaur', 'alwar', 'bikaner', 'churu',
       'jhunjhunun', 'ganganagar', 'hanumangarh', 'kanniyakumari',
       'tirunelveli', 'toothukudi', 'ramanathapuram', 'virudhunagar',
       'sivaganga', 'theni', 'madurai', 'pudukkottai', 'dindigul',
       'thanjavur', 'tiruchirappalli', 'nagapattinam', 'thiruvarur',
       'tirupur', 'coimbatore', 'karur', 'ariyalur', 'namakkal',
       'perambalur', 'erode', 'cuddalore', 'nilgiris', 'salem',
       'viluppuram', 'dharmapuri', 'tiruvanamalai', 'krishnagiri',
       'kancheepuram', 'vellore', 'thiruvallur', 'chennai',
       'warangal urban', 'south tripura', 'sipahijala', 'west tripura',
       'north tripura', 'gomati', 'khowai', 'dhalai', 'unakoti',
       'sonbhadra', 'lalitpur', 'mirzapur', 'chandauli', 'allahabad',
       'chitrakoot', 'jhansi', 'banda', 'sant ravidas nagar', 'varanasi',
       'mahoba', 'kaushambi', 'fatehpur', 'ghazipur', 'jaunpur', 'ballia',
       'azamgarh', 'rae bareli', 'maunathbhanjan', 'jalaun', 'sultanpur',
       'c s m nagar', 'kanpur nagar', 'deoria', 'kanpur dehat',
       'gorakhpur', 'ambedkar nagar', 'unnav', 'auraiya',
       'sant kabir nagar', 'barabanki', 'etawah', 'faizabad', 'lucknow',
       'kushinagar', 'basti', 'agra', 'gonda', 'kannauj', 'maharajganj',
       'mainpuri', 'hardoi', 'firozabad', 'siddharth nagar',
       'farrukhabad', 'sitapur', 'mathura', 'etah', 'bahraich', 'hathras',
       'shrawasti', 'shahjahanpur', 'kashi ram nagar', 'aligarh',
       'lakhimpur kheri', 'budaun', 'gautam buddha nagar', 'bulandshahar',
       'sambhal', 'bareilly', 'pilibhit', 'jyotiba phule nagar', 'rampur',
       'hapur', 'moradabad', 'ghaziabad', 'meerut', 'bagpat', 'bijnor',
       'muzaffarnagar', 'shamli', 'saharanpur', 'udham singh nagar',
       'nainital', 'champawat', 'almora', 'hardwar', 'pithoragarh',
       'garhwal', 'bageshwar', 'dehradun', 'chamoli', 'tehri garhwal',
       'uttarkashi', 'rudraprayag', 'purba medinipur',
       'south twenty four parganas', 'paschim medinipur', 'haora',
       'north twenty four parganas', 'hugli', 'bankura', 'puruliya',
       'nadia', 'barddhaman', 'birbhum', 'murshidabad', 'maldah',
       'dakshin dinajpur', 'uttar dinajpur', 'koch bihar', 'alipurduar',
       'darjiling', 'jalpaiguri'], dtype=object)

In [ ]:
df["district_name"] = df["district_name"].str.replace(r"\s+", " ", regex=True)

In [ ]:
df["district_name"] = df["district_name"].str.replace("-", " ")

In [ ]:
df["district_name"] = df["district_name"].str.strip()

In [ ]:
district_mapping = {
    "haora": "howrah",
    "barddhaman": "purba bardhaman",
    "koch bihar": "cooch behar",
    "hardwar": "haridwar",
    "tiruvanamalai": "tiruvannamalai"
}

df["district_name"] = df["district_name"].replace(district_mapping)

In [ ]:
df["district_name"].nunique()

668

In [ ]:
df["facility_type"] = df["facility_type"].str.lower().str.strip()
df["type_of_facility"] = df["type_of_facility"].str.lower().str.strip()
df["location_type"] = df["location_type"].str.lower().str.strip()

In [ ]:
df["facility_type"].unique()

array(['chc', 'dis_h', 'phc', 'sub_cen', 's_t_h'], dtype=object)

In [ ]:
df["type_of_facility"].unique()

array(['public', nan, '6534843245'], dtype=object)

In [ ]:
df["location_type"].unique()

array(['rural', 'urban', 'public'], dtype=object)

In [ ]:
df["type_of_facility"] = df["type_of_facility"].replace("6534843245", None)

In [ ]:
df["type_of_facility"] = df["type_of_facility"].str.lower().str.strip()

In [ ]:
df["location_type"] = df["location_type"].replace("public", None)

In [ ]:
df["location_type"] = df["location_type"].str.lower().str.strip()

In [ ]:
df["facility_type"].unique()

array(['chc', 'dis_h', 'phc', 'sub_cen', 's_t_h'], dtype=object)

In [ ]:
df["type_of_facility"].unique()

array(['public', nan, None], dtype=object)

In [ ]:
df["location_type"].unique()

array(['rural', 'urban', None], dtype=object)

In [ ]:
df

,state_name,district_name,subdistrict_name,facility_type,facility_name,facility_address,latitude,longitude,activeflag_c,notional_physical,location_type,type_of_facility,nin_n
0,andaman and nicobar islands,nicobar,nancowry,chc,CHC Nancowry,Kamorta,7.961090,93.558900,Y,Physical,rural,public,NaN
1,andaman and nicobar islands,south andaman,ferrargunj,chc,CHC Bambooflat,NaN,11.730300,92.650030,Y,Physical,rural,public,NaN
2,andaman and nicobar islands,north and middle andaman,rangat,chc,CHC Rangat,NaN,12.716090,92.905790,Y,Physical,rural,public,NaN
3,andaman and nicobar islands,north and middle andaman,diglipur,chc,CHC Diglipur,NaN,13.306820,92.941100,Y,Physical,rural,public,NaN
4,andaman and nicobar islands,nicobar,car nicobar,dis_h,BJR Hospital,NaN,9.148930,92.755780,Y,Physical,rural,public,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200433,west bengal,darjiling,kalimpong ii,sub_cen,Ladan SC,NaN,27.122209,88.658811,Y,Physical,rural,public,NaN
200434,west bengal,darjiling,kalimpong ii,sub_cen,N. Sakyong SC,NaN,27.132033,88.604083,Y,Physical,rural,public,NaN
200435,west bengal,darjiling,kalimpong ii,sub_cen,Kagay SC,NaN,27.158283,88.624917,Y,Physical,rural,public,NaN
200436,west bengal,darjiling,kalimpong ii,sub_cen,Palyong SC,NaN,27.164767,88.670850,Y,Physical,rural,public,NaN
200437,west bengal,darjiling,kalimpong ii,sub_cen,Rangpoo SC,NaN,27.172350,88.526683,Y,Physical,rural,public,NaN

In [ ]:
df.duplicated().sum()

np.int64(28)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df["latitude"].isnull().sum()

np.int64(63)

In [ ]:
df["longitude"].isnull().sum()

np.int64(80)

In [ ]:
df = df.dropna(subset=["latitude", "longitude"])

In [ ]:
df["latitude"].isnull().sum()

np.int64(0)

In [ ]:
df["longitude"].isnull().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(200330, 13)

In [ ]:
df = df.rename(columns={
    "state_name": "state",
    "district_name": "district",
    "subdistrict_name": "subdistrict",
    "facility_type": "facility_code",
    "facility_name": "facility",
    "facility_address": "address",
    "latitude": "lat",
    "longitude": "lon",
    "activeflag_c": "active",
    "notional_physical": "facility_status",
    "location_type": "location",
    "type_of_facility": "facility_owner",
    "nin_n": "facility_id"
})

In [ ]:
df.columns

Index(['state', 'district', 'subdistrict', 'facility_code', 'facility',
       'address', 'lat', 'lon', 'active', 'facility_status', 'location',
       'facility_owner', 'facility_id'],
      dtype='object')

In [ ]:
df.to_csv("geocode_health_centre_clean.csv", index=False)

#NFHS Health

In [ ]:
nfhs = pd.read_csv("NFHS_5_India_Districts_Factsheet_Data.csv", low_memory=False)

In [ ]:
nfhs.shape

(707, 109)

In [ ]:
nfhs.head()

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.0,23.0,973,927,98.0,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.7,19.8,950,844,100.0,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.7,21.0,967,935,96.5,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8
3,Srikakulam,Andhra Pradesh,874,780,100,60.0,20.7,1140,1163,95.0,...,14.4,5.5,22.9,1.0,0.2,3.8,7.1,21.3,0.6,28.3
4,Vizianagaram,Andhra Pradesh,902,853,134,56.0,20.6,1114,898,95.4,...,14.8,6.4,25.1,4.9,0.6,7.3,11.4,21.5,0.8,32.3

In [ ]:
nfhs.columns

Index(['District Names', 'State/UT', 'Number of Households surveyed',
       'Number of Women age 15-49 years interviewed',
       'Number of Men age 15-54 years interviewed',
       'Female population age 6 years and above who ever attended school (%)',
       'Population below age 15 years (%)',
       ' Sex ratio of the total population (females per 1,000 males)',
       'Sex ratio at birth for children born in the last five years (females per 1,000 males)',
       'Children under age 5 years whose birth was registered with the civil authority (%)',
       ...
       'Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%)',
       'Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ≥160 mm of Hg and/or Diastolic ≥100 mm of Hg) (%)',
       'Men age 15 years and above wih Elevated blood pressure (Systolic ≥140 mm of Hg and/or Diastolic ≥90 mm of Hg) or taking medicine to control blood pressure (%)',
       'Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%)',
       'Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%)',
       'Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%)',
       'Women age 15 years and above who use any kind of tobacco (%)',
       'Men age 15 years and above who use any kind of tobacco (%)',
       'Women age 15 years and above who consume alcohol (%)',
       'Men age 15 years and above who consume alcohol (%)'],
      dtype='object', length=109)

In [ ]:
nfhs.columns = nfhs.columns.str.strip()
nfhs.columns = nfhs.columns.str.lower()
nfhs.columns = nfhs.columns.str.replace(" ", "_")
nfhs.columns = nfhs.columns.str.replace("/", "_")
nfhs.columns = nfhs.columns.str.replace("(", "")
nfhs.columns = nfhs.columns.str.replace(")", "")
nfhs.columns = nfhs.columns.str.replace("%", "percent")

In [ ]:
nfhs.columns

Index(['district_names', 'state_ut', 'number_of_households_surveyed',
       'number_of_women_age_15-49_years_interviewed',
       'number_of_men_age_15-54_years_interviewed',
       'female_population_age_6_years_and_above_who_ever_attended_school_percent',
       'population_below_age_15_years_percent',
       'sex_ratio_of_the_total_population_females_per_1,000_males',
       'sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1,000_males',
       'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent',
       ...
       'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent',
       'women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent',
       'women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent',
       'women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent',
       'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'women_age_15_years_and_above_who_consume_alcohol_percent',
       'men_age_15_years_and_above_who_consume_alcohol_percent'],
      dtype='object', length=109)

In [ ]:
drop_cols = [
    "number_of_households_surveyed",
    "number_of_women_age_15-49_years_interviewed",
    "number_of_men_age_15-54_years_interviewed"
]

nfhs = nfhs.drop(columns=drop_cols)

In [ ]:
nfhs.shape

(707, 106)

In [ ]:
drop_cols = [

    "population_below_age_15_years_percent",
    "sex_ratio_of_the_total_population_females_per_1,000_males",
    "sex_ratio_at_birth_for_children_born_in_the_last_five_years_females_per_1,000_males"
]

nfhs = nfhs.drop(columns=drop_cols)

In [ ]:
nfhs.columns

Index(['district_names', 'state_ut',
       'female_population_age_6_years_and_above_who_ever_attended_school_percent',
       'children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent',
       'deaths_in_the_last_3_years_registered_with_the_civil_authority_percent',
       'population_living_in_households_with_electricity_percent',
       'population_living_in_households_with_an_improved_drinking-water_source1_percent',
       'population_living_in_households_that_use_an_improved_sanitation_facility2_percent',
       'households_using_clean_fuel_for_cooking3_percent',
       'households_using_iodized_salt_percent',
       ...
       'men_age_15_years_and_above_wih_mildly_elevated_blood_pressure_systolic_140-159_mm_of_hg_and_or_diastolic_90-99_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_moderately_or_severely_elevated_blood_pressure_systolic_≥160_mm_of_hg_and_or_diastolic_≥100_mm_of_hg_percent',
       'men_age_15_years_and_above_wih_elevated_blood_pressure_systolic_≥140_mm_of_hg_and_or_diastolic_≥90_mm_of_hg_or_taking_medicine_to_control_blood_pressure_percent',
       'women_age_30-49_years_ever_undergone_a_screening_test_for_cervical_cancer_percent',
       'women_age_30-49_years_ever_undergone_a_breast_examination_for_breast_cancer_percent',
       'women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent',
       'women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent',
       'women_age_15_years_and_above_who_consume_alcohol_percent',
       'men_age_15_years_and_above_who_consume_alcohol_percent'],
      dtype='object', length=103)

In [ ]:
nfhs = nfhs.rename(columns={
    "district_names": "district",
    "state_ut": "state"
})

In [ ]:
nfhs["state"] = nfhs["state"].str.lower().str.strip()
nfhs["district"] = nfhs["district"].str.lower().str.strip()

In [ ]:
nfhs["state"].unique()

array(['andaman & nicobar islands', 'andhra pradesh', 'arunachal pradesh',
       'assam', 'bihar', 'chandigarh', 'chhattisgarh',
       'dadra and nagar haveli & daman and diu', 'goa', 'gujarat',
       'haryana', 'himachal pradesh', 'jammu & kashmir', 'jharkhand',
       'karnataka', 'kerala', 'ladakh', 'lakshadweep', 'madhya pradesh',
       'maharastra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
       'nct of delhi', 'odisha', 'puducherry', 'punjab', 'rajasthan',
       'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh',
       'uttarakhand', 'west bengal'], dtype=object)

In [ ]:
state_mapping = {
    "andaman & nicobar islands": "andaman and nicobar islands",
    "dadra and nagar haveli & daman and diu": "dadra and nagar haveli and daman and diu",
    "jammu & kashmir": "jammu and kashmir",
    "maharastra": "maharashtra",
    "nct of delhi": "delhi"
}

nfhs["state"] = nfhs["state"].replace(state_mapping)

In [ ]:
nfhs["state"].unique()

array(['andaman and nicobar islands', 'andhra pradesh',
       'arunachal pradesh', 'assam', 'bihar', 'chandigarh',
       'chhattisgarh', 'dadra and nagar haveli and daman and diu', 'goa',
       'gujarat', 'haryana', 'himachal pradesh', 'jammu and kashmir',
       'jharkhand', 'karnataka', 'kerala', 'ladakh', 'lakshadweep',
       'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram',
       'nagaland', 'delhi', 'odisha', 'puducherry', 'punjab', 'rajasthan',
       'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh',
       'uttarakhand', 'west bengal'], dtype=object)

In [ ]:
nfhs["district"].unique()

array(['nicobars', 'north & middle andaman', 'south andaman',
       'srikakulam', 'vizianagaram', 'visakhapatnam', 'east godavari',
       'west godavari', 'krishna', 'guntur', 'prakasam',
       'sri potti sriramulu nello', 'y.s.r.', 'kurnool', 'anantapur',
       'chittoor', 'tawang', 'west kameng', 'east kameng', 'papum pare',
       'upper subansiri', 'upper siang', 'changlang', 'lower subansiri',
       'dibang valley', 'lower dibang valley', 'anjaw', 'east siang',
       'kra daadi', 'kurung kumey', 'lohit', 'longding', 'namsai',
       'siang', 'tirap', 'west siang', 'kokrajhar', 'goalpara', 'barpeta',
       'morigaon', 'lakhimpur', 'dhemaji', 'tinsukia', 'dibrugarh',
       'golaghat', 'dima hasao', 'cachar', 'karimganj', 'hailakandi',
       'bongaigaon', 'chirang', 'kamrup', 'kamrup metropolitan',
       'nalbari', 'baksa', 'darrang', 'udalguri', 'biswanath',
       'charaideo', 'dhubri', 'hojai', 'jorhat', 'karbi anglong',
       'majuli', 'nagaon', 'sivasagar', 'sonitpur',
       'south salmara mancachar', 'west karbi anglong',
       'pashchim champaran', 'purba champaran', 'sheohar', 'sitamarhi',
       'madhubani', 'supaul', 'araria', 'kishanganj', 'purnia', 'katihar',
       'madhepura', 'saharsa', 'darbhanga', 'muzaffarpur', 'gopalganj',
       'siwan', 'saran', 'vaishali', 'samastipur', 'begusarai',
       'khagaria', 'bhagalpur', 'banka', 'munger', 'lakhisarai',
       'sheikhpura', 'nalanda', 'patna', 'bhojpur', 'buxar',
       'kaimur (bhabua)', 'rohtas', 'aurangabad', 'gaya', 'nawada',
       'jamui', 'jehanabad', 'arwal', 'chandigarh', 'koriya', 'jashpur',
       'raigarh', 'korba', 'janjgir - champa', 'kabeerdham',
       'rajnandgaon', 'mahasamund', 'dhamtari', 'uttar bastar kanker',
       'narayanpur', 'bijapur', 'balod', 'baloda bazar', 'balrampur',
       'bastar', 'bemetara', 'bilaspur', 'dantewada', 'durg',
       'gariyaband', 'kodagaon', 'mungeli', 'raipur', 'sukma', 'surajpur',
       'surguja', 'diu', 'daman', 'dadra & nagar haveli', 'north goa',
       'south goa', 'kachchh', 'banas kantha', 'patan', 'mahesana',
       'gandhinagar', 'porbandar', 'amreli', 'anand', 'dohad', 'narmada',
       'bharuch', 'the dangs', 'navsari', 'valsad', 'surat', 'tapi',
       'ahmadabad', 'aravali', 'bhavnagar', 'botad', 'chhota udaipur',
       'devbhumi dwarka', 'gir somnath', 'jamnagar', 'junagadh', 'kheda',
       'mahisagar', 'morbi', 'panch mahals', 'rajkot', 'sabar kantha',
       'surendranagar', 'vadodara', 'panchkula', 'ambala', 'yamunanagar',
       'kurukshetra', 'kaithal', 'karnal', 'panipat', 'sonipat', 'jind',
       'fatehabad', 'sirsa', 'hisar', 'rohtak', 'jhajjar', 'mahendragarh',
       'rewari', 'gurgaon', 'mewat', 'faridabad', 'palwal', 'bhiwani',
       'charkhi dadri', 'chamba', 'kangra', 'lahul & spiti', 'kullu',
       'mandi', 'hamirpur', 'una', 'solan', 'sirmaur', 'shimla',
       'kinnaur', 'kupwara', 'badgam', 'punch', 'rajouri', 'kathua',
       'baramula', 'bandipore', 'srinagar', 'ganderbal', 'pulwama',
       'shupiyan', 'anantnag', 'kulgam', 'doda', 'ramban', 'kishtwar',
       'udhampur', 'reasi', 'jammu', 'samba', 'garhwa', 'chatra',
       'kodarma', 'giridih', 'deoghar', 'godda', 'sahibganj', 'pakur',
       'dhanbad', 'bokaro', 'lohardaga', 'purbi singhbhum', 'palamu',
       'latehar', 'hazaribagh', 'ramgarh', 'dumka', 'jamtara', 'ranchi',
       'khunti', 'gumla', 'simdega', 'pashchimi singhbhum',
       'saraikela-kharsawan', 'belgaum', 'bagalkot', 'bidar', 'raichur',
       'koppal', 'gadag', 'dharwad', 'uttara kannada', 'haveri',
       'bellary', 'chitradurga', 'davanagere', 'shimoga', 'udupi',
       'chikmagalur', 'tumkur', 'bangalore', 'mandya', 'hassan',
       'dakshina kannada', 'kodagu', 'mysore', 'chamarajanagar',
       'gulbarga', 'yadgir', 'kolar', 'chikkaballapura',
       'bangalore rural', 'ramanagara', 'kasaragod', 'kannur', 'wayanad',
       'kozhikode', 'malappuram', 'palakkad', 'thrissur', 'ernakulam',
       'idukki', 'kottayam', 'alappuzha', 'pathanamthitta', 'kollam',
       'thiruvananthapuram', 'leh(ladakh)', 'kargil', 'lakshadweep',
       'sheopur', 'morena', 'bhind', 'gwalior', 'datia', 'shivpuri',
       'tikamgarh', 'chhatarpur', 'panna', 'sagar', 'damoh', 'satna',
       'rewa', 'umaria', 'neemuch', 'mandsaur', 'ratlam', 'ujjain',
       'dewas', 'dhar', 'indore', 'khargone (west nimar)', 'barwani',
       'rajgarh', 'vidisha', 'bhopal', 'sehore', 'raisen', 'betul',
       'harda', 'hoshangabad', 'katni', 'jabalpur', 'narsimhapur',
       'dindori', 'mandla', 'chhindwara', 'seoni', 'balaghat', 'guna',
       'ashoknagar', 'shahdol', 'anuppur', 'sidhi', 'singrauli', 'jhabua',
       'alirajpur', 'khandwa (east nimar)', 'burhanpur', 'agar malwa',
       'shajapur', 'nandurbar', 'dhule', 'jalgaon', 'buldana', 'akola',
       'washim', 'amravati', 'wardha', 'nagpur', 'bhandara', 'gondiya',
       'gadchiroli', 'chandrapur', 'yavatmal', 'nanded', 'hingoli',
       'parbhani', 'jalna', 'nashik', 'mumbai suburban', 'mumbai', 'pune',
       'ahmadnagar', 'bid', 'latur', 'osmanabad', 'solapur', 'satara',
       'ratnagiri', 'sindhudurg', 'kolhapur', 'sangli', 'palghar',
       'thane', 'senapati', 'tamenglong', 'churachandpur', 'bishnupur',
       'thoubal', 'imphal west', 'imphal east', 'ukhrul', 'chandel',
       'south garo hills', 'ribhoi', 'east khasi hills',
       'east garo hills', 'east jantia hills', 'north garo hills',
       'south west garo hills', 'south west khasi hills',
       'west garo hills', 'west jaintia hills', 'west khasi hills',
       'mamit', 'kolasib', 'aizawl', 'champhai', 'serchhip', 'lunglei',
       'lawngtlai', 'mon', 'mokokchung', 'zunheboto', 'wokha', 'dimapur',
       'phek', 'tuensang', 'longleng', 'kiphire', 'kohima', 'peren',
       'central', 'east', 'new delhi', 'north', 'north east',
       'north west', 'shahdara', 'south', 'south east', 'south west',
       'west', 'bargarh', 'jharsuguda', 'sambalpur', 'debagarh',
       'sundargarh', 'kendujhar', 'mayurbhanj', 'baleshwar', 'bhadrak',
       'kendrapara', 'jagatsinghapur', 'cuttack', 'jajapur', 'dhenkanal',
       'anugul', 'nayagarh', 'khordha', 'puri', 'ganjam', 'gajapati',
       'kandhamal', 'baudh', 'subarnapur', 'balangir', 'nuapada',
       'kalahandi', 'rayagada', 'nabarangapur', 'koraput', 'malkangiri',
       'yanam', 'puducherry', 'mahe', 'karaikal', 'kapurthala',
       'jalandhar', 'hoshiarpur', 'shahid bhagat singh nagar',
       'fatehgarh sahib', 'ludhiana', 'moga', 'muktsar', 'faridkot',
       'bathinda', 'mansa', 'patiala', 'amritsar', 'tarn taran',
       'rupnagar', 'sahibzada ajit singh nagar', 'sangrur', 'barnala',
       'fazilka', 'firozpur', 'gurdaspur', 'pathankot', 'ganganagar',
       'hanumangarh', 'bikaner', 'churu', 'jhunjhunun', 'alwar',
       'bharatpur', 'dhaulpur', 'karauli', 'sawai madhopur', 'dausa',
       'jaipur', 'sikar', 'nagaur', 'jodhpur', 'jaisalmer', 'barmer',
       'jalor', 'sirohi', 'pali', 'ajmer', 'tonk', 'bundi', 'bhilwara',
       'rajsamand', 'dungarpur', 'banswara', 'chittaurgarh', 'kota',
       'baran', 'jhalawar', 'udaipur', 'pratapgarh', 'north  district',
       'west district', 'south district', 'east district', 'thiruvallur',
       'chennai', 'kancheepuram', 'vellore', 'tiruvannamalai',
       'viluppuram', 'salem', 'namakkal', 'erode', 'the nilgiris',
       'dindigul', 'karur', 'tiruchirappalli', 'perambalur', 'ariyalur',
       'cuddalore', 'nagapattinam', 'thiruvarur', 'thanjavur',
       'pudukkottai', 'sivaganga', 'madurai', 'theni', 'virudhunagar',
       'ramanathapuram', 'thoothukkudi', 'tirunelveli', 'kanniyakumari',
       'dharmapuri', 'krishnagiri', 'coimbatore', 'tiruppur', 'adilabad',
       'bhadradri kothagudem', 'hyderabad', 'jagitial', 'jangoan',
       'jayashankar bhupalapally', 'jogulamba gadwal', 'kamareddy',
       'karimnagar', 'khammam', 'komaram bheem asifabad', 'mahabubabad',
       'mahabubnagar', 'mancherial', 'medak', 'medchal-malkajgiri',
       'nagarkurnool', 'nalgonda', 'nirmal', 'nizamabad', 'peddapalli',
       'rajanna sircilla', 'ranga reddy', 'sangareddy', 'siddipet',
       'suryapet', 'vikarabad', 'wanaparthy', 'warangal rural',
       'warangal urban', 'yadadri bhuvanagiri', 'dhalai', 'gomati',
       'khowai', 'north tripura', 'sepahijala', 'south tripura',
       'unakoti', 'west tripura', 'saharanpur', 'bijnor', 'rampur',
       'jyotiba phule nagar', 'meerut', 'baghpat', 'gautam buddha nagar',
       'bulandshahr', 'aligarh', 'mahamaya nagar', 'mathura', 'agra',
       'firozabad', 'mainpuri', 'bareilly', 'pilibhit', 'shahjahanpur',
       'kheri', 'sitapur', 'hardoi', 'unnao', 'lucknow', 'farrukhabad',
       'kannauj', 'etawah', 'auraiya', 'kanpur dehat', 'kanpur nagar',
       'jalaun', 'jhansi', 'lalitpur', 'mahoba', 'banda', 'chitrakoot',
       'fatehpur', 'kaushambi', 'allahabad', 'bara banki', 'faizabad',
       'ambedkar nagar', 'bahraich', 'shrawasti', 'gonda',
       'siddharthnagar', 'basti', 'sant kabir nagar', 'mahrajganj',
       'gorakhpur', 'kushinagar', 'deoria', 'azamgarh', 'mau', 'ballia',
       'jaunpur', 'ghazipur', 'chandauli', 'varanasi',
       'sant ravidas nagar (bhadohi)', 'mirzapur', 'sonbhadra', 'etah',
       'kanshiram nagar', 'amethi', 'budaun', 'ghaziabad', 'hapur',
       'moradabad', 'muzaffarnagar', 'rae bareli', 'sambhal', 'shamli',
       'sultanpur', 'uttarkashi', 'chamoli', 'rudraprayag',
       'tehri garhwal', 'dehradun', 'garhwal', 'pithoragarh', 'bageshwar',
       'almora', 'champawat', 'nainital', 'udham singh nagar', 'hardwar',
       'darjiling', 'jalpaiguri', 'koch bihar', 'uttar dinajpur',
       'dakshin dinajpur', 'maldah', 'murshidabad', 'birbhum', 'nadia',
       'north twenty four pargana', 'hugli', 'bankura', 'puruliya',
       'haora', 'kolkata', 'south twenty four pargana',
       'paschim medinipur', 'purba medinipur', 'paschim barddhaman',
       'purba barddhaman'], dtype=object)

In [ ]:
nfhs["district"] = nfhs["district"].str.lower().str.strip()

nfhs["district"] = nfhs["district"].str.replace("&", "and", regex=False)
nfhs["district"] = nfhs["district"].str.replace("-", " ", regex=False)
nfhs["district"] = nfhs["district"].str.replace(r"\s+", " ", regex=True)

In [ ]:
district_mapping = {
    "north and middle andaman": "north and middle andaman",
    "sri potti sriramulu nello": "nellore",
    "y.s.r.": "ysr kadapa",
    "bangalore": "bengaluru urban",
    "mysore": "mysuru",
    "ahmadabad": "ahmedabad",
    "kodagaon": "kondagaon",
    "lahul and spiti": "lahaul and spiti",
    "punch": "poonch",
    "shupiyan": "shopian",
    "narsimhapur": "narsinghpur",
    "bid": "beed",
    "thoothukkudi": "tuticorin",
    "haora": "howrah",
    "hardwar": "haridwar"
}

nfhs["district"] = nfhs["district"].replace(district_mapping)

In [ ]:
geo_districts = set(df["district"])
nfhs_districts = set(nfhs["district"])

missing_districts = nfhs_districts - geo_districts

missing_districts

{'ahmadnagar',
 'aizawl',
 'amethi',
 'aravali',
 'ashoknagar',
 'bagalkot',
 'baghpat',
 'bandipore',
 'bara banki',
 'beed',
 'bemetara',
 'bengaluru urban',
 'bhadradri kothagudem',
 'biswanath',
 'bulandshahr',
 'chamarajanagar',
 'charaideo',
 'charkhi dadri',
 'chhindwara',
 'chhota udaipur',
 'chikkaballapura',
 'debagarh',
 'dohad',
 'east district',
 'east jantia hills',
 'hojai',
 'jagatsinghapur',
 'jagitial',
 'jangoan',
 'jayashankar bhupalapally',
 'jogulamba gadwal',
 'kabeerdham',
 'kaimur (bhabua)',
 'kamareddy',
 'kamrup',
 'kamrup metropolitan',
 'kanshiram nagar',
 'karimnagar',
 'kendujhar',
 'khandwa (east nimar)',
 'khargone (west nimar)',
 'kheri',
 'koch bihar',
 'kolkata',
 'komaram bheem asifabad',
 'kozhikode',
 'lahaul and spiti',
 'leh(ladakh)',
 'mahabubabad',
 'mahabubnagar',
 'mahamaya nagar',
 'mahrajganj',
 'majuli',
 'mancherial',
 'mau',
 'medchal malkajgiri',
 'morigaon',
 'mumbai',
 'mumbai suburban',
 'mysuru',
 'nagarkurnool',
 'nicobars',
 'nirmal',
 'north district',
 'north twenty four pargana',
 'pakur',
 'paschim barddhaman',
 'pashchim champaran',
 'peddapalli',
 'puducherry',
 'purba barddhaman',
 'purba champaran',
 'rajanna sircilla',
 'ramanagara',
 'ribhoi',
 'sahibzada ajit singh nagar',
 'sangareddy',
 'sant ravidas nagar (bhadohi)',
 'saraikela kharsawan',
 'sepahijala',
 'shahid bhagat singh nagar',
 'siddharthnagar',
 'siddipet',
 'singrauli',
 'sivasagar',
 'south district',
 'south salmara mancachar',
 'south twenty four pargana',
 'subarnapur',
 'suryapet',
 'the nilgiris',
 'tiruppur',
 'tuticorin',
 'unnao',
 'uttar bastar kanker',
 'vikarabad',
 'visakhapatnam',
 'wanaparthy',
 'warangal rural',
 'west district',
 'west karbi anglong',
 'yadadri bhuvanagiri',
 'ysr kadapa'}

In [ ]:
district_mapping = {
    "ahmadnagar": "ahmednagar",
    "koch bihar": "cooch behar",
    "the nilgiris": "nilgiris",
    "bara banki": "barabanki",
    "morigaon": "marigaon",
    "siddharthnagar": "siddharth nagar"
}

nfhs["district"] = nfhs["district"].replace(district_mapping)

In [ ]:
nfhs["district"] = nfhs["district"].str.replace(" district", "", regex=False)

In [ ]:
missing_districts = set(nfhs["district"]) - set(df["district"])
missing_districts

{'aizawl',
 'amethi',
 'aravali',
 'ashoknagar',
 'bagalkot',
 'baghpat',
 'bandipore',
 'beed',
 'bemetara',
 'bengaluru urban',
 'bhadradri kothagudem',
 'biswanath',
 'bulandshahr',
 'chamarajanagar',
 'charaideo',
 'charkhi dadri',
 'chhindwara',
 'chhota udaipur',
 'chikkaballapura',
 'debagarh',
 'dohad',
 'east jantia hills',
 'hojai',
 'jagatsinghapur',
 'jagitial',
 'jangoan',
 'jayashankar bhupalapally',
 'jogulamba gadwal',
 'kabeerdham',
 'kaimur (bhabua)',
 'kamareddy',
 'kamrup',
 'kamrup metropolitan',
 'kanshiram nagar',
 'karimnagar',
 'kendujhar',
 'khandwa (east nimar)',
 'khargone (west nimar)',
 'kheri',
 'kolkata',
 'komaram bheem asifabad',
 'kozhikode',
 'lahaul and spiti',
 'leh(ladakh)',
 'mahabubabad',
 'mahabubnagar',
 'mahamaya nagar',
 'mahrajganj',
 'majuli',
 'mancherial',
 'mau',
 'medchal malkajgiri',
 'mumbai',
 'mumbai suburban',
 'mysuru',
 'nagarkurnool',
 'nicobars',
 'nirmal',
 'north twenty four pargana',
 'pakur',
 'paschim barddhaman',
 'pashchim champaran',
 'peddapalli',
 'puducherry',
 'purba barddhaman',
 'purba champaran',
 'rajanna sircilla',
 'ramanagara',
 'ribhoi',
 'sahibzada ajit singh nagar',
 'sangareddy',
 'sant ravidas nagar (bhadohi)',
 'saraikela kharsawan',
 'sepahijala',
 'shahid bhagat singh nagar',
 'siddipet',
 'singrauli',
 'sivasagar',
 'south salmara mancachar',
 'south twenty four pargana',
 'subarnapur',
 'suryapet',
 'tiruppur',
 'tuticorin',
 'unnao',
 'uttar bastar kanker',
 'vikarabad',
 'visakhapatnam',
 'wanaparthy',
 'warangal rural',
 'west karbi anglong',
 'yadadri bhuvanagiri',
 'ysr kadapa'}

In [ ]:
district_mapping = {
    "aravali": "arvalli",
    "beed": "bid",
    "bengaluru urban": "bangalore urban",
    "chikkaballapura": "chikballapur",
    "dohad": "dahod",
    "jagatsinghapur": "jagatsinghpur",
    "kozhikode": "kozhikkode",
    "mysuru": "mysore",
    "tuticorin": "thoothukudi",
    "visakhapatnam": "vishakapatnam"
}

nfhs["district"] = nfhs["district"].replace(district_mapping)

In [ ]:
missing = set(nfhs["district"]) - set(df["district"])
missing

{'aizawl',
 'amethi',
 'arvalli',
 'ashoknagar',
 'bagalkot',
 'baghpat',
 'bandipore',
 'bemetara',
 'bhadradri kothagudem',
 'biswanath',
 'bulandshahr',
 'chamarajanagar',
 'charaideo',
 'charkhi dadri',
 'chhindwara',
 'chhota udaipur',
 'chikballapur',
 'debagarh',
 'east jantia hills',
 'hojai',
 'jagitial',
 'jangoan',
 'jayashankar bhupalapally',
 'jogulamba gadwal',
 'kabeerdham',
 'kaimur (bhabua)',
 'kamareddy',
 'kamrup',
 'kamrup metropolitan',
 'kanshiram nagar',
 'karimnagar',
 'kendujhar',
 'khandwa (east nimar)',
 'khargone (west nimar)',
 'kheri',
 'kolkata',
 'komaram bheem asifabad',
 'lahaul and spiti',
 'leh(ladakh)',
 'mahabubabad',
 'mahabubnagar',
 'mahamaya nagar',
 'mahrajganj',
 'majuli',
 'mancherial',
 'mau',
 'medchal malkajgiri',
 'mumbai',
 'mumbai suburban',
 'nagarkurnool',
 'nicobars',
 'nirmal',
 'north twenty four pargana',
 'pakur',
 'paschim barddhaman',
 'pashchim champaran',
 'peddapalli',
 'puducherry',
 'purba barddhaman',
 'purba champaran',
 'rajanna sircilla',
 'ramanagara',
 'ribhoi',
 'sahibzada ajit singh nagar',
 'sangareddy',
 'sant ravidas nagar (bhadohi)',
 'saraikela kharsawan',
 'sepahijala',
 'shahid bhagat singh nagar',
 'siddipet',
 'singrauli',
 'sivasagar',
 'south salmara mancachar',
 'south twenty four pargana',
 'subarnapur',
 'suryapet',
 'thoothukudi',
 'tiruppur',
 'unnao',
 'uttar bastar kanker',
 'vikarabad',
 'wanaparthy',
 'warangal rural',
 'west karbi anglong',
 'yadadri bhuvanagiri',
 'ysr kadapa'}

In [ ]:
district_mapping = {
    "kaimur (bhabua)": "kaimur bhabua",
    "khandwa (east nimar)": "khandwa",
    "khargone (west nimar)": "khargone",
    "leh(ladakh)": "leh",
    "north twenty four pargana": "north 24 parganas",
    "south twenty four pargana": "south 24 parganas",
    "paschim barddhaman": "paschim bardhaman",
    "purba barddhaman": "purba bardhaman",
    "pashchim champaran": "west champaran",
    "purba champaran": "east champaran",
    "sant ravidas nagar (bhadohi)": "bhadohi"
}

nfhs["district"] = nfhs["district"].replace(district_mapping)

In [ ]:
missing = set(nfhs["district"]) - set(df["district"])
len(missing), missing

(80,
 {'aizawl',
  'amethi',
  'arvalli',
  'ashoknagar',
  'bagalkot',
  'baghpat',
  'bandipore',
  'bemetara',
  'bhadohi',
  'bhadradri kothagudem',
  'biswanath',
  'bulandshahr',
  'chamarajanagar',
  'charaideo',
  'charkhi dadri',
  'chhindwara',
  'chhota udaipur',
  'chikballapur',
  'debagarh',
  'east jantia hills',
  'hojai',
  'jagitial',
  'jangoan',
  'jayashankar bhupalapally',
  'jogulamba gadwal',
  'kabeerdham',
  'kamareddy',
  'kamrup',
  'kamrup metropolitan',
  'kanshiram nagar',
  'karimnagar',
  'kendujhar',
  'kheri',
  'kolkata',
  'komaram bheem asifabad',
  'lahaul and spiti',
  'leh',
  'mahabubabad',
  'mahabubnagar',
  'mahamaya nagar',
  'mahrajganj',
  'majuli',
  'mancherial',
  'mau',
  'medchal malkajgiri',
  'mumbai',
  'mumbai suburban',
  'nagarkurnool',
  'nicobars',
  'nirmal',
  'north 24 parganas',
  'pakur',
  'paschim bardhaman',
  'peddapalli',
  'puducherry',
  'rajanna sircilla',
  'ramanagara',
  'ribhoi',
  'sahibzada ajit singh nagar',
  'sangareddy',
  'saraikela kharsawan',
  'sepahijala',
  'shahid bhagat singh nagar',
  'siddipet',
  'singrauli',
  'sivasagar',
  'south 24 parganas',
  'south salmara mancachar',
  'subarnapur',
  'suryapet',
  'thoothukudi',
  'tiruppur',
  'unnao',
  'uttar bastar kanker',
  'vikarabad',
  'wanaparthy',
  'warangal rural',
  'west karbi anglong',
  'yadadri bhuvanagiri',
  'ysr kadapa'})

In [ ]:
nfhs = nfhs.replace('%','',regex=True)
nfhs = nfhs.apply(pd.to_numeric, errors='ignore')

/tmp/ipykernel_760/182053706.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  nfhs = nfhs.apply(pd.to_numeric, errors='ignore')

In [ ]:
nfhs.isnull().sum()

district                                                                                   0
state                                                                                      0
female_population_age_6_years_and_above_who_ever_attended_school_percent                   0
children_under_age_5_years_whose_birth_was_registered_with_the_civil_authority_percent     0
deaths_in_the_last_3_years_registered_with_the_civil_authority_percent                     0
                                                                                          ..
women_age_30-49_years_ever_undergone_an_oral_cavity_examination_for_oral_cancer_percent    0
women_age_15_years_and_above_who_use_any_kind_of_tobacco_percent                           0
men_age_15_years_and_above_who_use_any_kind_of_tobacco_percent                             0
women_age_15_years_and_above_who_consume_alcohol_percent                                   0
men_age_15_years_and_above_who_consume_alcohol_percent                                     0
Length: 103, dtype: int64

In [ ]:
nfhs.to_csv("nfhs_clean_district_health.csv", index=False)

#pollution

In [ ]:
poll = pd.read_csv("3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69 (1).csv")

In [ ]:
poll

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,NH3,3.0,4.0,4.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,SO2,10.0,14.0,12.0
2,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,PM10,78.0,241.0,146.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,SO2,7.0,105.0,35.0
4,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",03-03-2026 15:00:00,27.103358,93.679645,SO2,9.0,10.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...
3324,India,West_Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",03-03-2026 15:00:00,22.511060,88.351420,CO,28.0,111.0,39.0
3325,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",03-03-2026 15:00:00,22.544808,88.340369,PM10,72.0,193.0,139.0
3326,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",03-03-2026 15:00:00,22.544808,88.340369,CO,38.0,109.0,47.0
3327,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",03-03-2026 15:00:00,22.544808,88.340369,OZONE,8.0,89.0,62.0
3328,India,West_Bengal,Siliguri,"Ward-32 Bapupara, Siliguri - WBPCB",03-03-2026 15:00:00,26.687923,88.415250,PM2.5,44.0,117.0,81.0

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
df.columns = df.columns.str.replace(" ", "_")

In [ ]:
df["state"] = df["state"].str.lower()
df["state"] = df["state"].str.replace("_", " ")
df["state"] = df["state"].str.strip()

In [ ]:
poll.shape

(3329, 11)

In [ ]:
poll.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude',
       'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max',
       'pollutant_avg'],
      dtype='object')

In [ ]:
poll.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,NH3,3.0,4.0,4.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,SO2,10.0,14.0,12.0
2,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,PM10,78.0,241.0,146.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,SO2,7.0,105.0,35.0
4,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",03-03-2026 15:00:00,27.103358,93.679645,SO2,9.0,10.0,10.0

In [ ]:
poll.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,NH3,3.0,4.0,4.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",03-03-2026 15:00:00,16.554731,80.649110,SO2,10.0,14.0,12.0
2,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,PM10,78.0,241.0,146.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",03-03-2026 15:00:00,17.720000,83.300000,SO2,7.0,105.0,35.0
4,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",03-03-2026 15:00:00,27.103358,93.679645,SO2,9.0,10.0,10.0

In [ ]:
poll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3329 entries, 0 to 3328
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3329 non-null   object
 1   state          3329 non-null   object
 2   city           3329 non-null   object
 3   station        3329 non-null   object
 4   last_update    3329 non-null   object
 5   latitude       3329 non-null   float64
 6   longitude      3329 non-null   float64
 7   pollutant_id   3329 non-null   object
 8   pollutant_min  3195 non-null   float64
 9   pollutant_max  3195 non-null   float64
 10  pollutant_avg  3195 non-null   float64
dtypes: float64(5), object(6)
memory usage: 286.2+ KB

In [ ]:
poll.columns = poll.columns.str.strip().str.lower()
poll.columns = poll.columns.str.replace(" ", "_")

In [ ]:
poll["state"] = poll["state"].str.lower()
poll["state"] = poll["state"].str.replace("_", " ")
poll["state"] = poll["state"].str.strip()

In [ ]:
poll["state"].unique()

array(['andhra pradesh', 'arunachal pradesh', 'assam', 'bihar',
       'chhattisgarh', 'delhi', 'chandigarh', 'gujarat', 'haryana',
       'himachal pradesh', 'jammu and kashmir', 'karnataka',
       'maharashtra', 'madhya pradesh', 'kerala', 'meghalaya', 'mizoram',
       'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan',
       'tamilnadu', 'telangana', 'sikkim', 'tripura', 'uttar pradesh',
       'uttarakhand', 'west bengal', 'andaman and nicobar', 'jharkhand'],
      dtype=object)

In [ ]:
state_mapping = {
    "tamilnadu": "tamil nadu",
    "andaman and nicobar": "andaman and nicobar islands"
}

poll["state"] = poll["state"].replace(state_mapping)

In [ ]:
poll["state"].unique()

array(['andhra pradesh', 'arunachal pradesh', 'assam', 'bihar',
       'chhattisgarh', 'delhi', 'chandigarh', 'gujarat', 'haryana',
       'himachal pradesh', 'jammu and kashmir', 'karnataka',
       'maharashtra', 'madhya pradesh', 'kerala', 'meghalaya', 'mizoram',
       'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan',
       'tamil nadu', 'telangana', 'sikkim', 'tripura', 'uttar pradesh',
       'uttarakhand', 'west bengal', 'andaman and nicobar islands',
       'jharkhand'], dtype=object)

In [ ]:
poll["last_update"] = pd.to_datetime(poll["last_update"])

In [ ]:
poll["last_update"].dtype

dtype('<M8[ns]')

In [ ]:
poll["pollutant_min"] = pd.to_numeric(poll["pollutant_min"], errors="coerce")
poll["pollutant_max"] = pd.to_numeric(poll["pollutant_max"], errors="coerce")
poll["pollutant_avg"] = pd.to_numeric(poll["pollutant_avg"], errors="coerce")

In [ ]:
poll.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    134
pollutant_max    134
pollutant_avg    134
dtype: int64

In [ ]:
poll["state"].unique()
poll["last_update"].dtype
poll.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    134
pollutant_max    134
pollutant_avg    134
dtype: int64

In [ ]:
poll = poll.dropna(subset=["pollutant_min","pollutant_max","pollutant_avg"])

In [ ]:
poll.isnull().sum()

country          0
state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [ ]:
poll.duplicated().sum()

np.int64(0)

In [ ]:
poll.shape

(3195, 11)

In [ ]:
poll

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,andhra pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",2026-03-03 15:00:00,16.554731,80.649110,NH3,3.0,4.0,4.0
1,India,andhra pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",2026-03-03 15:00:00,16.554731,80.649110,SO2,10.0,14.0,12.0
2,India,andhra pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",2026-03-03 15:00:00,17.720000,83.300000,PM10,78.0,241.0,146.0
3,India,andhra pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",2026-03-03 15:00:00,17.720000,83.300000,SO2,7.0,105.0,35.0
4,India,arunachal pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",2026-03-03 15:00:00,27.103358,93.679645,SO2,9.0,10.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...
3324,India,west bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",2026-03-03 15:00:00,22.511060,88.351420,CO,28.0,111.0,39.0
3325,India,west bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,PM10,72.0,193.0,139.0
3326,India,west bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,CO,38.0,109.0,47.0
3327,India,west bengal,Kolkata,"Victoria, Kolkata - WBPCB",2026-03-03 15:00:00,22.544808,88.340369,OZONE,8.0,89.0,62.0
3328,India,west bengal,Siliguri,"Ward-32 Bapupara, Siliguri - WBPCB",2026-03-03 15:00:00,26.687923,88.415250,PM2.5,44.0,117.0,81.0

In [ ]:
poll["pollutant_id"].unique()

array(['NH3', 'SO2', 'PM10', 'OZONE', 'PM2.5', 'NO2', 'CO'], dtype=object)

In [ ]:
poll["pollutant_id"] = poll["pollutant_id"].str.lower().str.strip()

/tmp/ipykernel_760/495055302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poll["pollutant_id"] = poll["pollutant_id"].str.lower().str.strip()

In [ ]:
poll["pollutant_id"] = poll["pollutant_id"].replace({
    "ozone": "o3"
})

/tmp/ipykernel_760/428258788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poll["pollutant_id"] = poll["pollutant_id"].replace({

In [ ]:
poll["pollutant_id"].unique()

array(['nh3', 'so2', 'pm10', 'o3', 'pm2.5', 'no2', 'co'], dtype=object)

In [ ]:
poll_ml = poll.pivot_table(
    index=["state","city"],
    columns="pollutant_id",
    values="pollutant_avg",
    aggfunc="mean"
).reset_index()

In [ ]:
poll_ml.columns.name = None

In [ ]:
poll_ml.head()

,state,city,co,nh3,no2,o3,pm10,pm2.5,so2
0,andhra pradesh,Amaravati,24.0,4.0,24.0,40.0,117.0,68.0,15.0
1,andhra pradesh,Anantapur,17.0,5.0,25.0,34.0,65.0,60.0,16.0
2,andhra pradesh,Chittoor,38.0,6.0,29.0,37.0,55.0,60.0,13.0
3,andhra pradesh,Kadapa,42.0,4.0,21.0,14.0,82.0,60.0,16.0
4,andhra pradesh,Rajamahendravaram,24.0,4.0,30.0,20.0,92.0,75.0,16.0

In [ ]:
poll_ml["city"] = poll_ml["city"].str.lower().str.strip()

In [ ]:
poll.to_csv("pollution_raw_dataset.csv", index=False)

In [ ]:
poll_ml.to_csv("pollution_ml_features.csv", index=False)

#Health infrastructure dataset

In [ ]:
infra = pd.read_csv("RS_Session_257_AU_282_1 (1).csv")

infra.head()

,S. No.,State/UT,PHCs - Rural,PHCs - Urban,PHCs - Total,CHCs - Rural,CHCs - Urban,CHCs - Total
0,1,Andhra Pradesh,1142,259,1401,141,57,198
1,2,Arunachal Pradesh,122,5,127,57,0,57
2,3,Assam,948,53,1001,197,2,199
3,4,Bihar,1932,102,2034,306,0,306
4,5,Chhattisgarh,769,52,821,166,3,169

In [ ]:
infra.shape

(36, 8)

In [ ]:
infra.columns

Index(['S. No.', 'State/UT', 'PHCs - Rural', 'PHCs - Urban', 'PHCs - Total',
       'CHCs - Rural', 'CHCs - Urban', 'CHCs - Total'],
      dtype='object')

In [ ]:
infra.columns = infra.columns.str.lower()
infra.columns = infra.columns.str.replace(" ", "_")
infra.columns = infra.columns.str.replace("/", "_")
infra.columns = infra.columns.str.replace("-", "_")
infra.columns = infra.columns.str.replace(".", "")

In [ ]:
infra.columns

Index(['s_no', 'state_ut', 'phcs___rural', 'phcs___urban', 'phcs___total',
       'chcs___rural', 'chcs___urban', 'chcs___total'],
      dtype='object')

In [ ]:
infra.columns = [
    "s_no",
    "state",
    "phc_rural",
    "phc_urban",
    "phc_total",
    "chc_rural",
    "chc_urban",
    "chc_total"
]

In [ ]:
infra.columns

Index(['s_no', 'state', 'phc_rural', 'phc_urban', 'phc_total', 'chc_rural',
       'chc_urban', 'chc_total'],
      dtype='object')

In [ ]:
infra["state"] = infra["state"].str.lower().str.strip()

In [ ]:
infra["state"].unique()

array(['andhra pradesh', 'arunachal pradesh', 'assam', 'bihar',
       'chhattisgarh', 'goa', 'gujarat', 'haryana', 'himachal pradesh',
       'jharkhand', 'karnataka', 'kerala', 'madhya pradesh',
       'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
       'odisha', 'punjab', 'rajasthan', 'sikkim', 'tamil nadu',
       'telangana', 'tripura', 'uttarakhand', 'uttar pradesh',
       'west bengal', 'andaman and nicobar islands', 'chandigarh',
       'dadra and nagar haveli and daman and diu', 'delhi',
       'jammu and kashmir', 'ladakh', 'lakshadweep', 'puducherry'],
      dtype=object)

In [ ]:
infra["state"] = (
    infra["state"]
    .str.lower()
    .str.strip()
    .str.replace("&", "and")
)

In [ ]:
state_fix = {
    "andaman and nicobar": "andaman and nicobar islands",
    "nct of delhi": "delhi"
}

infra["state"] = infra["state"].replace(state_fix)

In [ ]:
infra["state"].unique()

array(['andhra pradesh', 'arunachal pradesh', 'assam', 'bihar',
       'chhattisgarh', 'goa', 'gujarat', 'haryana', 'himachal pradesh',
       'jharkhand', 'karnataka', 'kerala', 'madhya pradesh',
       'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
       'odisha', 'punjab', 'rajasthan', 'sikkim', 'tamil nadu',
       'telangana', 'tripura', 'uttarakhand', 'uttar pradesh',
       'west bengal', 'andaman and nicobar islands', 'chandigarh',
       'dadra and nagar haveli and daman and diu', 'delhi',
       'jammu and kashmir', 'ladakh', 'lakshadweep', 'puducherry'],
      dtype=object)

In [ ]:
infra.isnull().sum()

s_no         0
state        0
phc_rural    0
phc_urban    0
phc_total    0
chc_rural    0
chc_urban    0
chc_total    0
dtype: int64

In [ ]:
infra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   s_no       36 non-null     int64
 1   state      36 non-null     object
 2   phc_rural  36 non-null     int64
 3   phc_urban  36 non-null     int64
 4   phc_total  36 non-null     int64
 5   chc_rural  36 non-null     int64
 6   chc_urban  36 non-null     int64
 7   chc_total  36 non-null     int64
dtypes: int64(7), object(1)
memory usage: 2.4+ KB

In [ ]:
infra.to_csv("health_infrastructure_clean.csv", index=False)